# Generated by Django 6.0.8 on 2026-09-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_executionevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='execution',
            new_name='execution_e_workspa_cddae4_idx',
            old_name='execution_e_workspa_f72dda_idx',
        ),
        migrations.RenameIndex(
            model_name='execution',
            new_name='execution_e_object__0c68dc_idx',
            old_name='execution_e_object__3bd452_idx',
        ),
        migrations.RenameIndex(
            model_name='executionevent',
            new_name='execution_e_executi_b4f99b_idx',
            old_name='execution_e_executi_7e4d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='executionevent',
            new_name='execution_e_event_t_325be2_idx',
            old_name='execution_e_event_t_a9c317_idx',
        ),
    ]
