import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("datasources","0001_initial"),("workspaces","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name="SourceBinding",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("source_schema",models.CharField(blank=True,max_length=180)),("source_table",models.CharField(max_length=180)),("access_mode",models.CharField(choices=[("LIVE","Live"),("IMPORTED","Platform copy")],default="IMPORTED",max_length=20)),("primary_key_fields",models.JSONField(blank=True,default=list)),("cursor_field",models.CharField(blank=True,max_length=180)),("last_refresh_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="source_bindings_created",to=settings.AUTH_USER_MODEL)),("platform_asset",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="source_bindings",to="datasources.dataasset")),("source",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="platform_bindings",to="datasources.datasource")),("workspace",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="source_bindings",to="workspaces.workspace"))],options={"ordering":["source_table"]}),
      migrations.AddConstraint(model_name="sourcebinding",constraint=models.UniqueConstraint(fields=("source","source_schema","source_table"),name="unique_source_table_binding")),
      migrations.CreateModel(name="PublishPlan",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("name",models.CharField(max_length=180)),("scope",models.CharField(choices=[("SCHEMA","Schema"),("DATA","Data"),("SCHEMA_DATA","Schema + data")],default="DATA",max_length=20)),("status",models.CharField(choices=[("DRAFT","Draft"),("REVIEWED","Reviewed"),("APPROVED","Approved"),("RUNNING","Running"),("SUCCEEDED","Succeeded"),("FAILED","Failed"),("CANCELLED","Cancelled")],default="DRAFT",max_length=20)),("schema_changes",models.JSONField(blank=True,default=list)),("data_changes",models.JSONField(blank=True,default=dict)),("generated_sql",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("binding",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="publish_plans",to="datasources.sourcebinding")),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="publish_plans_created",to=settings.AUTH_USER_MODEL)),("source",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="publish_plans",to="datasources.datasource")),("workspace",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="publish_plans",to="workspaces.workspace"))],options={"ordering":["-created_at"]}),
      migrations.CreateModel(name="WritebackPolicy",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("source_schema",models.CharField(blank=True,max_length=180)),("source_table",models.CharField(max_length=180)),("allowed_operations",models.JSONField(blank=True,default=list)),("allowed_fields",models.JSONField(blank=True,default=list)),("key_fields",models.JSONField(blank=True,default=list)),("validation_rules",models.JSONField(blank=True,default=dict)),("enabled",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="writeback_policies_created",to=settings.AUTH_USER_MODEL)),("source",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="writeback_policies",to="datasources.datasource")),("workspace",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="writeback_policies",to="workspaces.workspace"))],options={"ordering":["source_table"]}),
      migrations.AddConstraint(model_name="writebackpolicy",constraint=models.UniqueConstraint(fields=("source","source_schema","source_table"),name="unique_writeback_policy_per_source_table")),
    ]
