"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useWorkspace} from "@/lib/hooks/useWorkspace";
import {listComputeTargets,createComputeTarget,listEnvironments,createEnvironment,addEnvironmentPackage,retryEnvironmentPackage,searchPyPIPackages,getPyPIPackage,syncInstalledEnvironmentPackages} from "@/lib/services/environments";
const arr=v=>Array.isArray(v)?v:v?.results||[];
const alias=n=>n?.toLowerCase()==="sklearn"?"scikit-learn":n;
export default function PackageExplorer(){
 const {activeWorkspace}=useWorkspace(); const [targets,setTargets]=useState([]),[envs,setEnvs]=useState([]),[query,setQuery]=useState(""),[results,setResults]=useState([]),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[version,setVersion]=useState(""),[busy,setBusy]=useState(false),[searching,setSearching]=useState(false),[error,setError]=useState("");
 async function load(sync=false){if(!activeWorkspace)return;let [t,e]=await Promise.all([listComputeTargets(activeWorkspace.id),listEnvironments(activeWorkspace.id)]);let next=arr(e);const chosen=next[0]?.id||"";if(sync&&chosen){try{await syncInstalledEnvironmentPackages(chosen);e=await listEnvironments(activeWorkspace.id);next=arr(e)}catch{}}setTargets(arr(t));setEnvs(next)}
 useEffect(()=>{load(true)},[activeWorkspace?.id]);
 useEffect(()=>{if(query.trim().length<2){setResults([]);setError("");return} const timer=setTimeout(async()=>{setSearching(true);setError("");try{setResults(arr(await searchPyPIPackages(query.trim())))}catch(e){setError(e?.response?.data?.detail||"PyPI search is unavailable.")}finally{setSearching(false)}},550);return()=>clearTimeout(timer)},[query]);
 const env=envs[0]; const installed=useMemo(()=>new Map((env?.packages||[]).map(x=>[x.name.toLowerCase(),x])),[env]);
 async function choose(pkg){const canonical=alias(pkg.name);setSelected({...pkg,name:canonical});setDetail(null);setVersion("");try{const d=await getPyPIPackage(canonical);setDetail(d);setVersion(d.version||"")}catch{setDetail({name:canonical,version:"",versions:[]})}}
 async function ensureEnv(){if(env)return env;let target=targets.find(x=>x.kind==="CUSTOMER");if(!target)target=await createComputeTarget({workspace:activeWorkspace.id,name:"Customer compute",kind:"CUSTOMER",status:"ACTIVE",capabilities:{runtime:"isolated-python"}});return await createEnvironment({workspace:activeWorkspace.id,name:"Python",python_version:"3.14",compute_target:target.id,status:"ACTIVE",version:1})}
 async function install(){if(!selected||!activeWorkspace)return;setBusy(true);setError("");try{const e=await ensureEnv();const name=alias(detail?.name||selected.name);const existing=(e.packages||[]).find(x=>x.name.toLowerCase()===name.toLowerCase())||installed.get(name.toLowerCase());if(existing){await retryEnvironmentPackage(existing.id)}else{await addEnvironmentPackage({environment:e.id,name,version_spec:version||"",status:"REQUESTED",source:"PYPI"})}setSelected(null);setDetail(null);setQuery("");setResults([]);await load(true)}catch(e){setError(e?.response?.data?.detail||JSON.stringify(e?.response?.data||{})||"Package installation could not be queued.")}finally{setBusy(false)}}
 return <div className="pageStack packageExplorerPage"><header className="pageHeader pageHeaderActions platformSettingsHeader"><div><h1>Packages</h1><p className="pageSubtitle">Search PyPI and install packages into an isolated Code environment.</p></div><Link className="button secondaryButton packageNavButton" href="/app/environments">← Python environments</Link></header>
 <div className="packageExplorerIntro"><strong>PyPI package catalog</strong><span>Installed packages are synchronized from the selected environment. Search results are shown as compact rows.</span></div>
 {env?<div className="packageEnvironmentPicker"><span>Workspace Python</span><strong>v{env.version}</strong></div>:null}
 <input className="packageSearch packageCatalogSearch" autoFocus placeholder="Search PyPI packages (example: scikit-learn, matplotlib, xgboost)" value={query} onChange={e=>setQuery(e.target.value)}/>{searching&&<small className="packageSearchStatus">Searching PyPI…</small>}{error&&<div className="inlineError">{error}</div>}
 <div className="packageCatalog packageCatalogPage packageCatalogRows">{results.map(x=>{const canonical=alias(x.name);const p=installed.get(canonical.toLowerCase());const ready=p?.status==="INSTALLED";return <button key={x.name} className={`packageCatalogItem ${selected?.name===canonical?"selected":""}`} onClick={()=>choose(x)}><span className="packageCheck">{ready?"✓":selected?.name===canonical?"✓":""}</span><strong>{canonical}</strong><span className="packageCatalogSource">PyPI</span><span className={`packageStatus ${(p?.status||"available").toLowerCase()}`}>{p?.status||"AVAILABLE"}</span><span>{p?.installed_version||""}</span></button>})}{query.trim().length>=2&&!searching&&!results.length&&!error&&<div className="packageEmpty">No packages found.</div>}</div>
 {selected&&<section className="packageInstallPanel"><div><strong>{detail?.name||selected.name}</strong>{detail?.summary&&<p>{detail.summary}</p>}</div><label>Version<select value={version} onChange={e=>setVersion(e.target.value)}><option value="">Latest</option>{(detail?.versions||[]).map(v=><option key={v} value={v}>{v}</option>)}</select></label><button className="button primaryButton" disabled={busy} onClick={install}>{busy?"Queueing…":installed.has((detail?.name||selected.name).toLowerCase())?"Retry install":"Install"}</button></section>}
 </div>
}
