export const API_ENDPOINTS = {
  scripts: { list: "/scripts/", detail: (id) => `/scripts/${id}/`, analyze: "/scripts/analyze/" },
  environments: { targets: "/compute-targets/", list: "/python-environments/", packages: "/environment-packages/" },
  auth: {
    register: "/auth/register/",
    token: "/auth/token/",
    refresh: "/auth/token/refresh/",
    me: "/auth/me/",
  },
  health: {
    live: "/health/live/",
    ready: "/health/ready/",
  },
  operations: {
    status: "/ops/status/",
  },
  data: {
    sources: "/data/sources/",
    sourceDetail: (sourceId) => `/data/sources/${sourceId}/`,
    assets: "/data/assets/",
    assetDetail: (assetId) => `/data/assets/${assetId}/`,
    sourceBindings: "/data/source-bindings/",
    publishPlans: "/data/publish-plans/",
    writebackPolicies: "/data/writeback-policies/",
  },
  catalog: {
    tables: "/catalog/tables/",
    tableDetail: (tableId) => `/catalog/tables/${tableId}/`,
    relations: "/catalog/relations/",
    sync: (sourceId) => `/catalog/sources/${sourceId}/sync/`,
    managedTables: "/catalog/managed-tables/",
    managedTableDetail: (tableId) => `/catalog/managed-tables/${tableId}/`,
    fieldContentRules: "/catalog/field-content-rules/",
    fieldContentRuleDetail: (id) => `/catalog/field-content-rules/${id}/`,
    platformFields: "/catalog/platform-fields/",
  },
  records: {
    collection: (tableId) => `/records/tables/${tableId}/`,
    detail: (tableId, recordKey) =>
      `/records/tables/${tableId}/${encodeURIComponent(recordKey)}/`,
  },

  views: {
    list: "/views/",
    detail: (viewId) => `/views/${viewId}/`,
    schema: (viewId) => `/views/${viewId}/schema/`,
    data: (viewId) => `/views/${viewId}/data/`,
    validate: (viewId) => `/views/${viewId}/validate/`,
    bindings: (viewId) => `/views/${viewId}/bindings/`,
    bindingDetail: (viewId, bindingId) => `/views/${viewId}/bindings/${bindingId}/`,
    actions: (viewId) => `/views/${viewId}/actions/`,
    interact: (viewId) => `/views/${viewId}/interact/`,
    builder: (viewId) => `/views/${viewId}/builder/`,
    operationalQuery: (viewId) => `/views/${viewId}/operational-query/`,
    operationalWriteback: (viewId) => `/views/${viewId}/operational-writeback/`,
  },
  transformations: {
    list: "/transformations/",
    detail: (id) => `/transformations/${id}/`,
    preview: (id) => `/transformations/${id}/preview/`,
    run: (id) => `/transformations/${id}/run/`,
  },
  dependencies: {
    edges: "/dependencies/edges/",
    edgeDetail: (id) => `/dependencies/edges/${id}/`,
    states: "/dependencies/states/",
    events: "/dependencies/events/",
    lineage: (assetId) => `/dependencies/lineage/${assetId}/`,
  },
  executions: {
    list: "/executions/",
    detail: (id) => `/executions/${id}/`,
    cancel: (id) => `/executions/${id}/cancel/`,
    events: (id) => `/executions/${id}/events/`,
  },
  metrics: {
    semanticModels: "/metrics/semantic-models/",
    semanticModelDetail: (id) => `/metrics/semantic-models/${id}/`,
    dimensions: "/metrics/dimensions/",
    dimensionDetail: (id) => `/metrics/dimensions/${id}/`,
    list: "/metrics/",
    detail: (id) => `/metrics/${id}/`,
    query: (id) => `/metrics/${id}/query/`,
  },
  analytics: {
    charts: "/analytics/charts/",
    chartDetail: (id) => `/analytics/charts/${id}/`,
    chartDataset: (id) => `/analytics/charts/${id}/dataset/`,
    chartDrilldown: (id) => `/analytics/charts/${id}/drilldown/`,
    dashboards: "/analytics/dashboards/",
    dashboardDetail: (id) => `/analytics/dashboards/${id}/`,
    dashboardDataset: (id) => `/analytics/dashboards/${id}/dataset/`,
    dashboardItems: "/analytics/dashboard-items/",
    dashboardItemDetail: (id) => `/analytics/dashboard-items/${id}/`,
    reports: "/analytics/reports/",
    reportDetail: (id) => `/analytics/reports/${id}/`,
  },
  dataScience: {
    pythonTransformations: "/data-science/python-transformations/",
    pythonTransformationDetail: (id) => `/data-science/python-transformations/${id}/`,
    pythonTransformationInputs: (id) => `/data-science/python-transformations/${id}/inputs/`,
    pythonTransformationRun: (id) => `/data-science/python-transformations/${id}/run/`,
    datasets: "/data-science/datasets/",
    datasetDetail: (id) => `/data-science/datasets/${id}/`,
    models: "/data-science/models/",
    modelDetail: (id) => `/data-science/models/${id}/`,
    modelTrain: (id) => `/data-science/models/${id}/train/`,
    runs: "/data-science/runs/",
    runDetail: (id) => `/data-science/runs/${id}/`,
    versions: "/data-science/versions/",
    versionDetail: (id) => `/data-science/versions/${id}/`,
    versionInfer: (id) => `/data-science/versions/${id}/infer/`,
    predictions: "/data-science/predictions/",
    predictionDetail: (id) => `/data-science/predictions/${id}/`,
  },
  optimization: {
    models: "/optimization/models/",
    modelDetail: (id) => `/optimization/models/${id}/`,
    modelValidate: (id) => `/optimization/models/${id}/validate/`,
    modelRun: (id) => `/optimization/models/${id}/run/`,
    parameters: "/optimization/parameters/",
    parameterDetail: (id) => `/optimization/parameters/${id}/`,
    variables: "/optimization/variables/",
    variableDetail: (id) => `/optimization/variables/${id}/`,
    objectives: "/optimization/objectives/",
    objectiveDetail: (id) => `/optimization/objectives/${id}/`,
    constraints: "/optimization/constraints/",
    constraintDetail: (id) => `/optimization/constraints/${id}/`,
    solverConfigs: "/optimization/solver-configs/",
    solverConfigDetail: (id) => `/optimization/solver-configs/${id}/`,
    scenarios: "/optimization/scenarios/",
    scenarioDetail: (id) => `/optimization/scenarios/${id}/`,
    runs: "/optimization/runs/",
    runDetail: (id) => `/optimization/runs/${id}/`,
    solutions: "/optimization/solutions/",
    solutionDetail: (id) => `/optimization/solutions/${id}/`,
  },
  importExport: {
    imports: "/import-export/imports/",
    importPreview: (id) => `/import-export/imports/${id}/preview/`,
    importRun: (id) => `/import-export/imports/${id}/run/`,
    syncPolicies: "/import-export/sync-policies/",
    syncPolicyDetail: (id) => `/import-export/sync-policies/${id}/`,
    syncPolicyRun: (id) => `/import-export/sync-policies/${id}/run/`,
    exports: "/import-export/exports/",
    exportDownload: (id) => `/import-export/exports/${id}/download/`,
  },
  governance: {
    audit: "/governance/audit/",
    permissions: "/governance/permissions/",
    permissionDetail: (id) => `/governance/permissions/${id}/`,
    quota: (workspaceId) => `/governance/workspaces/${workspaceId}/quota/`,
    usage: (workspaceId) => `/governance/workspaces/${workspaceId}/usage/`,
    policy: (workspaceId) => `/governance/workspaces/${workspaceId}/policy/`,
    retention: (workspaceId) => `/governance/workspaces/${workspaceId}/retention/`,
    members: (workspaceId) => `/governance/workspaces/${workspaceId}/members/`,
    secrets: "/governance/datasource-secrets/",
    secretDetail: (sourceId) => `/governance/datasource-secrets/${sourceId}/`,
    destructiveRequests: "/governance/destructive-requests/",
    destructiveApprove: (id) => `/governance/destructive-requests/${id}/approve/`,
    copyEvents: "/governance/copy-events/",
  },
  gateway: {
    registrations: "/gateway/registrations/",
    register: "/gateway/registrations/register/",
    renew: (id) => `/gateway/registrations/${id}/renew-enrollment/`,
    revoke: (id) => `/gateway/registrations/${id}/revoke/`,
    bindings: "/gateway/bindings/",
    bindingDetail: (id) => `/gateway/bindings/${id}/`,
    jobs: "/gateway/jobs/",
    queue: (sourceId) => `/gateway/jobs/sources/${sourceId}/queue/`,
    imports: "/gateway/imports/",
  },
  connectors: {
    test: (sourceId) => `/connectors/sources/${sourceId}/test/`,
    catalog: (sourceId) => `/connectors/sources/${sourceId}/catalog/`,
    read: (sourceId) => `/connectors/sources/${sourceId}/read/`,
  },
  workspaces: {
    organizations: "/workspaces/organizations/",
    organizationDetail: (organizationId) => `/workspaces/organizations/${organizationId}/`,
    list: "/workspaces/",
    detail: (workspaceId) => `/workspaces/${workspaceId}/`,
  },
};
