"use client";
import {useMemo,useState} from "react";
import ManageTabs from "@/components/manage/ManageTabs";
import Alert from "@/components/ui/Alert";
import EmptyState from "@/components/ui/EmptyState";
import Icon from "@/components/ui/Icon";
import {useWorkspace} from "@/lib/hooks/useWorkspace";
import {createOrganization,updateOrganization,deleteOrganization,createWorkspace,updateWorkspace,deleteWorkspace} from "@/lib/services/workspaces";
import {getApiErrorMessage} from "@/lib/utils/errors";
const slugify=v=>String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function StructurePage(){
 const {organizations,workspaces,activeWorkspace,setActiveWorkspace,refresh,isLoading}=useWorkspace();
 const [expanded,setExpanded]=useState({}),[draft,setDraft]=useState(null),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState({type:"",text:""});
 const grouped=useMemo(()=>Object.fromEntries(organizations.map(o=>[o.id,workspaces.filter(w=>w.organization===o.id)])),[organizations,workspaces]);
 const canOrg=o=>["OWNER","ADMIN"].includes(o.current_user_role),canWs=o=>["OWNER","ADMIN","BUILDER"].includes(o.current_user_role);
 async function run(fn,text){setBusy(true);setMsg({type:"",text:""});try{await fn();await refresh();setDraft(null);setEdit(null);setMsg({type:"success",text})}catch(e){setMsg({type:"error",text:getApiErrorMessage(e)})}finally{setBusy(false)}}
 const startOrg=()=>setDraft({kind:"org",name:"",slug:"",status:"ACTIVE"});
 const startWs=o=>{setExpanded(x=>({...x,[o.id]:true}));setDraft({kind:"workspace",organization:o.id,name:"",slug:"",description:"",status:"ACTIVE"})};
 const saveDraft=()=>draft?.kind==="org"?run(()=>createOrganization({...draft,kind:undefined,slug:draft.slug||slugify(draft.name)}),"Organization created."):run(async()=>{const payload={organization:draft.organization,name:draft.name,slug:draft.slug||slugify(draft.name),description:draft.description,status:draft.status};const w=await createWorkspace(payload);setActiveWorkspace(w)},"Workspace created.");
 const saveEdit=()=>edit.kind==="org"?run(()=>updateOrganization(edit.id,{name:edit.name,slug:edit.slug,status:edit.status}),"Organization updated."):run(()=>updateWorkspace(edit.id,{organization:edit.organization,name:edit.name,slug:edit.slug,description:edit.description,status:edit.status}),"Workspace updated.");
 return <div className="pageStack"><header className="pageHeader"><h1>Structure</h1></header><ManageTabs/>{msg.text&&<Alert type={msg.type}>{msg.text}</Alert>}
 <section className="card structureCard"><div className="cardHeader"><h2>Organizations</h2><button className="iconButton" title="Add organization" aria-label="Add organization" disabled={!!draft||!!edit} onClick={startOrg}><Icon name="plus" size={17}/></button></div>
 {draft?.kind==="org"&&<div className="inlineGridRow orgRow draftRow"><input autoFocus placeholder="Organization name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value,slug:slugify(e.target.value)})}/><input placeholder="slug" value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})}/><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>ACTIVE</option><option>SUSPENDED</option><option>ARCHIVED</option></select><span>—</span><div className="inlineActions"><button className="iconButton" title="Save" disabled={busy||!draft.name.trim()} onClick={saveDraft}><Icon name="check"/></button><button className="iconButton" title="Discard" onClick={()=>setDraft(null)}><Icon name="close"/></button></div></div>}
 {isLoading&&!organizations.length?<p className="muted">Loading...</p>:!organizations.length?<EmptyState title="No organizations" description=""/>:<div className="structureTree"><div className="inlineGridHead orgRow"><span>Name</span><span>Slug</span><span>Status</span><span>Role</span><span></span></div>{organizations.map(o=>{const open=!!expanded[o.id],editing=edit?.kind==="org"&&edit.id===o.id;return <div className="structureNode" key={o.id}><div className="inlineGridRow orgRow clickableRow" onClick={()=>!editing&&setExpanded(x=>({...x,[o.id]:!open}))}>{editing?<><input value={edit.name} onClick={e=>e.stopPropagation()} onChange={e=>setEdit({...edit,name:e.target.value})}/><input value={edit.slug} onClick={e=>e.stopPropagation()} onChange={e=>setEdit({...edit,slug:e.target.value})}/><select value={edit.status} onClick={e=>e.stopPropagation()} onChange={e=>setEdit({...edit,status:e.target.value})}><option>ACTIVE</option><option>SUSPENDED</option><option>ARCHIVED</option></select><span>{o.current_user_role}</span><div className="inlineActions" onClick={e=>e.stopPropagation()}><button className="iconButton" onClick={saveEdit}><Icon name="check"/></button><button className="iconButton" onClick={()=>setEdit(null)}><Icon name="close"/></button></div></>:<><strong><Icon name={open?"chevronDown":"chevronRight"} size={14}/> {o.name}</strong><code>{o.slug}</code><span>{o.status}</span><span>{o.current_user_role}</span><div className="inlineActions" onClick={e=>e.stopPropagation()}><button className="iconButton" title="Edit" disabled={!canOrg(o)} onClick={()=>setEdit({kind:"org",...o})}><Icon name="edit"/></button><button className="iconButton" title="Remove organization" disabled={o.current_user_role!=="OWNER"} onClick={()=>window.confirm(`Remove ${o.name}?`)&&run(()=>deleteOrganization(o.id),"Organization removed.")}><Icon name="close"/></button></div></>}</div>
 {open&&<div className="workspaceBranch"><div className="workspaceBranchHeader"><strong>Workspaces</strong><button className="iconButton" title="Add workspace" disabled={!canWs(o)||!!draft||!!edit} onClick={()=>startWs(o)}><Icon name="plus" size={16}/></button></div><div className="inlineGridHead wsRow"><span>Name</span><span>Slug</span><span>Status</span><span>Description</span><span></span></div>{draft?.kind==="workspace"&&draft.organization===o.id&&<div className="inlineGridRow wsRow draftRow"><input autoFocus placeholder="Workspace name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value,slug:slugify(e.target.value)})}/><input value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})}/><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>ACTIVE</option><option>ARCHIVED</option></select><input placeholder="Description" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><div className="inlineActions"><button className="iconButton" disabled={!draft.name.trim()} onClick={saveDraft}><Icon name="check"/></button><button className="iconButton" onClick={()=>setDraft(null)}><Icon name="close"/></button></div></div>}{grouped[o.id].map(w=>{const editingW=edit?.kind==="workspace"&&edit.id===w.id;return <div className={`inlineGridRow wsRow ${activeWorkspace?.id===w.id?"activeTableRow":""}`} key={w.id}>{editingW?<><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><input value={edit.slug} onChange={e=>setEdit({...edit,slug:e.target.value})}/><select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option>ACTIVE</option><option>ARCHIVED</option></select><input value={edit.description||""} onChange={e=>setEdit({...edit,description:e.target.value})}/><div className="inlineActions"><button className="iconButton" onClick={saveEdit}><Icon name="check"/></button><button className="iconButton" onClick={()=>setEdit(null)}><Icon name="close"/></button></div></>:<><button className="structureNameButton" onClick={()=>setActiveWorkspace(w)}><strong>{w.name}</strong></button><code>{w.slug}</code><span>{w.status}</span><span>{w.description||"—"}</span><div className="inlineActions"><button className="iconButton" title="Edit" disabled={!canWs(o)} onClick={()=>setEdit({kind:"workspace",...w})}><Icon name="edit"/></button><button className="iconButton" title="Remove workspace" disabled={!canWs(o)} onClick={()=>window.confirm(`Remove ${w.name}?`)&&run(()=>deleteWorkspace(w.id),"Workspace removed.")}><Icon name="close"/></button></div></>}</div>})}</div>}</div>})}</div>}</section></div>}
