export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  APP: "/app",
  ORGANIZATIONS: "/app/organizations",
  WORKSPACES: "/app/workspaces",
  DATA_MODEL: "/app/data-model",
  RECORDS: "/app/records",
  VIEWS: "/app/views",
  TRANSFORMATIONS: "/app/transformations",
  DEPENDENCIES: "/app/dependencies",
  EXECUTIONS: "/app/executions",
  METRICS: "/app/metrics",
  ANALYTICS: "/app/analytics",
  DASHBOARDS: "/app/dashboards",
  REPORTS: "/app/reports",
  DATA_SCIENCE: "/app/data-science",
  OPTIMIZATION: "/app/optimization",
  IMPORT_EXPORT: "/app/import-export",
  GOVERNANCE: "/app/governance",
  CUSTOMER_GATEWAY: "/app/customer-gateway",
  OPERATIONS: "/app/operations",
};

export const PUBLIC_ROUTES = [ROUTES.LOGIN, ROUTES.REGISTER];
