"use client";
import {useEffect,useMemo,useState} from "react";
import ManageTabs from "@/components/manage/ManageTabs";import Alert from "@/components/ui/Alert";import EmptyState from "@/components/ui/EmptyState";import Spinner from "@/components/ui/Spinner";import Icon from "@/components/ui/Icon";import {useWorkspace} from "@/lib/hooks/useWorkspace";
import {approveDestructiveRequest,createDestructiveRequest,createPermission,getPolicy,getQuota,getRetention,listAudit,listCredentialStatus,listDestructiveRequests,listPermissions,setDataSourceSecret,updatePermission,updatePolicy,updateQuota,updateRetention,listWorkspaceMembers,listCopyEvents} from "@/lib/services/governance";import {listDataSources} from "@/lib/services/dataSources";import {listCatalogTables} from "@/lib/services/dataModel";import {getApiErrorMessage} from "@/lib/utils/errors";
const list=d=>Array.isArray(d)?d:d?.results||[];const ADMIN=["OWNER","ADMIN"];
const policyGroups=[["Data",[["allow_import","Import"],["allow_refresh","Refresh"],["allow_external_write","External write"],["allow_schema_changes","Schema changes"]]],["Operational",[["allow_operational_writeback","Writeback"],["allow_delete","Delete"]]],["Runtime",[["allow_platform_compute","Platform compute"],["allow_customer_compute","Customer compute"],["allow_customer_packages","Customer packages"]]],["Protection",[["require_ddl_approval","DDL approval"],["require_bulk_write_approval","Bulk write approval"]]]];
const quotaFields=[["max_storage_mb","Storage MB"],["max_import_rows","Max import rows"],["max_export_rows","Max export rows"],["max_concurrent_jobs","Concurrent jobs"],["max_python_runtime_seconds","Python runtime s"],["max_optimization_seconds","Optimization s"]];
const retentionFields=[["audit_log_days","Audit logs (days)"],["execution_log_days","Execution logs (days)"],["export_artifact_days","Export artifacts (days)"],["import_artifact_days","Import artifacts (days)"]];
const clone=x=>JSON.parse(JSON.stringify(x||{}));
function ScopeBar({items,value,onChange,locked,general=true,editing,onEdit,onSave,onDiscard,dirty,canEdit=true}){return <div className="governanceToolbar"><div className="governanceScope">{general&&<button className={`scopeButton ${value==="GENERAL"?"active":""}`} disabled={locked&&value!=="GENERAL"} onClick={()=>onChange("GENERAL")}>General</button>}{items.map(w=><button key={w.id} className={`scopeButton ${value===w.id?"active":""}`} disabled={locked&&value!==w.id} onClick={()=>onChange(w.id)}>{w.name}</button>)}</div><div className="governanceEditActions">{dirty&&<span className="governanceDirty">Unsaved changes</span>}{!editing?<button className="iconButton" title="Edit" disabled={!canEdit} onClick={onEdit}><Icon name="edit"/></button>:<><button className="iconButton" title="Save changes" onClick={onSave}><Icon name="check"/></button><button className="iconButton" title="Discard changes" onClick={onDiscard}><Icon name="close"/></button></>}</div></div>}
export default function Page(){
 const {activeWorkspace,organizations,workspaces}=useWorkspace();const org=useMemo(()=>organizations.find(x=>x.id===activeWorkspace?.organization),[organizations,activeWorkspace]);const orgWorkspaces=useMemo(()=>workspaces.filter(w=>w.organization===org?.id),[workspaces,org]);const isAdmin=ADMIN.includes(org?.current_user_role);
 const [tab,setTab]=useState("policies"),[scope,setScope]=useState("GENERAL"),[editingPolicy,setEditingPolicy]=useState(false),[dirtyPolicy,setDirtyPolicy]=useState(false),[policy,setPolicy]=useState(null),[quota,setQuota]=useState(null),[retention,setRetention]=useState(null),[baseline,setBaseline]=useState(null);
 const [audit,setAudit]=useState([]),[permissions,setPermissions]=useState([]),[requests,setRequests]=useState([]),[credentials,setCredentials]=useState([]),[secretEditing,setSecretEditing]=useState(null),[secretJson,setSecretJson]=useState("{}"),[destructive,setDestructive]=useState({action:"DROP_TABLE",resource_type:"TableAsset",resource_id:"",reason:""});
 const [accessWs,setAccessWs]=useState(""),[tables,setTables]=useState([]),[accessTable,setAccessTable]=useState(""),[members,setMembers]=useState([]),[accessRows,setAccessRows]=useState([]),[accessBaseline,setAccessBaseline]=useState([]),[editingAccess,setEditingAccess]=useState(false),[dirtyAccess,setDirtyAccess]=useState(false);
 const [changeSources,setChangeSources]=useState([]),[changeSource,setChangeSource]=useState(""),[copyEvents,setCopyEvents]=useState([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const selectedPolicyWs=scope==="GENERAL"?orgWorkspaces[0]:orgWorkspaces.find(w=>w.id===scope);
 async function loadPeripheral(){if(!activeWorkspace?.id)return;const [a,p,d,c]=await Promise.all([listAudit(activeWorkspace.id),listPermissions(),listDestructiveRequests(),listCredentialStatus(activeWorkspace.id)]);setAudit(list(a));setPermissions(list(p));setRequests(list(d).filter(x=>x.workspace===activeWorkspace.id));setCredentials(list(c));}
 async function loadPolicy(){if(!selectedPolicyWs?.id)return;setLoading(true);try{const [po,q,r]=await Promise.all([getPolicy(selectedPolicyWs.id),getQuota(selectedPolicyWs.id),getRetention(selectedPolicyWs.id)]);setPolicy(po);setQuota(q);setRetention(r);setBaseline({policy:clone(po),quota:clone(q),retention:clone(r)});setDirtyPolicy(false)}catch(e){setError(getApiErrorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{if(activeWorkspace?.id){setAccessWs(activeWorkspace.id);loadPeripheral().catch(e=>setError(getApiErrorMessage(e))) }},[activeWorkspace?.id]);
 useEffect(()=>{if(orgWorkspaces.length&&!orgWorkspaces.some(w=>w.id===scope)&&scope!=="GENERAL")setScope("GENERAL")},[org?.id]);
 useEffect(()=>{loadPolicy()},[scope,selectedPolicyWs?.id]);
 async function loadAccess(wsId){if(!wsId)return;setLoading(true);try{const [src,m,p]=await Promise.all([listDataSources(wsId),listWorkspaceMembers(wsId),listPermissions()]);const ss=list(src), all=[];for(const s of ss){const ts=list(await listCatalogTables(s.id));ts.forEach(t=>all.push({...t,source_name:s.name}))}setTables(all);setMembers(list(m));setPermissions(list(p));const next=all[0]?.id||"";setAccessTable(next);buildAccessRows(next,list(m),list(p),wsId)}catch(e){setError(getApiErrorMessage(e))}finally{setLoading(false)}}
 function buildAccessRows(tableId,memberList=members,permissionList=permissions,wsId=accessWs){const rows=memberList.map(u=>{const x=permissionList.find(p=>String(p.workspace)===String(wsId)&&String(p.user)===String(u.id)&&p.resource_type==="TableAsset"&&String(p.resource_id)===String(tableId));return {permission_id:x?.id||null,user:u.id,user_name:u.name,user_email:u.email,role:u.role,resource_type:"TableAsset",resource_id:tableId,field_name:x?.field_name||"",action:x?.action||"READ",effect:x?.effect||"ALLOW"}});setAccessRows(rows);setAccessBaseline(clone(rows));setDirtyAccess(false)}
 useEffect(()=>{if(tab==="access"&&accessWs)loadAccess(accessWs)},[tab,accessWs]);
 function changeScope(v){if(dirtyPolicy)return;setEditingPolicy(false);setScope(v)}
 function discardPolicy(){setPolicy(clone(baseline.policy));setQuota(clone(baseline.quota));setRetention(clone(baseline.retention));setDirtyPolicy(false);setEditingPolicy(false)}
 async function savePolicyAll(){try{setError("");const targets=scope==="GENERAL"?orgWorkspaces:[selectedPolicyWs];const clean=x=>Object.fromEntries(Object.entries(x||{}).filter(([k])=>!["workspace","updated_at"].includes(k)));await Promise.all(targets.flatMap(w=>[updatePolicy(w.id,clean(policy)),updateQuota(w.id,clean(quota)),updateRetention(w.id,clean(retention))]));setMessage(scope==="GENERAL"?"General settings applied to all current workspaces.":"Workspace governance updated.");setEditingPolicy(false);await loadPolicy()}catch(e){setError(getApiErrorMessage(e))}}
 const mutate=(setter,obj,k,v)=>{setter({...obj,[k]:v});setDirtyPolicy(true)};
 async function saveAccess(){try{setError("");for(const r of accessRows){const payload={workspace:accessWs,user:r.user,resource_type:"TableAsset",resource_id:accessTable,field_name:r.field_name,action:r.action,effect:r.effect};if(r.permission_id)await updatePermission(r.permission_id,payload);else await createPermission(payload)}setMessage("Access rules updated.");setEditingAccess(false);await loadAccess(accessWs)}catch(e){setError(getApiErrorMessage(e))}}
 function discardAccess(){setAccessRows(clone(accessBaseline));setDirtyAccess(false);setEditingAccess(false)}
 function selectAccessWs(id){if(dirtyAccess)return;setEditingAccess(false);setAccessWs(id)}function selectTable(id){if(dirtyAccess)return;setEditingAccess(false);setAccessTable(id);buildAccessRows(id)}
 async function saveSecret(){let parsed;try{parsed=JSON.parse(secretJson)}catch{return setError("Credentials must be valid JSON.")}await setDataSourceSecret(secretEditing.id,parsed);setSecretEditing(null);setSecretJson("{}");setMessage("Credential replaced securely.");await loadPeripheral()}
 useEffect(()=>{if(tab!=="changes"||!activeWorkspace?.id)return;(async()=>{try{const src=list(await listDataSources(activeWorkspace.id)).filter(x=>["EXTERNAL","PRIVATE_GATEWAY"].includes(x.mode));setChangeSources(src);const id=changeSource&&src.some(x=>x.id===changeSource)?changeSource:(src[0]?.id||"");if(id!==changeSource)setChangeSource(id);if(id)setCopyEvents(list(await listCopyEvents(activeWorkspace.id,id)));else setCopyEvents([])}catch(e){setError(getApiErrorMessage(e))}})()},[tab,activeWorkspace?.id,changeSource]);
 if(!activeWorkspace)return <EmptyState title="Selecciona un workspace" description="Governance requires an organization context."/>;
 return <div className="pageStack"><header className="pageHeader"><p className="eyebrow">Manage · Governance</p><h1>Governance</h1></header><ManageTabs/>{error&&<Alert type="error">{error}</Alert>}{message&&<Alert type="success">{message}</Alert>}<div className="tabBar">{[["policies","Policies"],["access","Access"],["credentials","Credentials"],["changes","Changes"],["audit","Audit"]].map(([v,l])=><button key={v} className={tab===v?"active":""} onClick={()=>setTab(v)}>{l}</button>)}</div>
 {tab==="policies"&&<><ScopeBar items={orgWorkspaces} value={scope} onChange={changeScope} locked={dirtyPolicy} editing={editingPolicy} onEdit={()=>setEditingPolicy(true)} onSave={savePolicyAll} onDiscard={discardPolicy} dirty={dirtyPolicy} canEdit={isAdmin}/>{loading?<Spinner label="Loading policies..."/>:<section className="card"><section className="governanceSection"><h2>Workspace policies</h2><div className="policyGrid">{policyGroups.map(([title,items])=><div className="policyGroup" key={title}><strong>{title}</strong>{items.map(([k,l])=><label className="policyLine" key={k}><span>{l}</span>{editingPolicy?<input type="checkbox" checked={!!policy?.[k]} onChange={e=>mutate(setPolicy,policy,k,e.target.checked)}/>:<span className="readValue">{policy?.[k]?"On":"Off"}</span>}</label>)}</div>)}</div></section><section className="governanceSection"><h2>Resource limits</h2><div className="formGrid">{quotaFields.map(([k,l])=><label key={k}>{l}{editingPolicy?<input type="number" value={quota?.[k]??0} onChange={e=>mutate(setQuota,quota,k,Number(e.target.value))}/>:<span className="readValue">{quota?.[k]??0}</span>}</label>)}</div></section><section className="governanceSection"><h2>Retention</h2><div className="formGrid">{retentionFields.map(([k,l])=><label key={k}>{l}{editingPolicy?<input type="number" value={retention?.[k]??0} onChange={e=>mutate(setRetention,retention,k,Number(e.target.value))}/>:<span className="readValue">{retention?.[k]??0}</span>}</label>)}</div></section></section>}</>}
 {tab==="access"&&<><ScopeBar general={false} items={orgWorkspaces} value={accessWs} onChange={selectAccessWs} locked={dirtyAccess} editing={editingAccess} onEdit={()=>setEditingAccess(true)} onSave={saveAccess} onDiscard={discardAccess} dirty={dirtyAccess} canEdit={isAdmin}/><section className="card"><div className="cardHeader"><h2>Tables</h2><span className="countBadge">{tables.length}</span></div>{tables.length?<div className="accessTablePicker">{tables.map(t=><button key={t.id} className={`scopeButton ${accessTable===t.id?"active":""}`} disabled={dirtyAccess&&accessTable!==t.id} onClick={()=>selectTable(t.id)}>{t.technical_name||t.table_name}</button>)}</div>:<EmptyState title="No tables" description="This workspace has no catalogued tables."/>}{accessTable&&<div className="dataTableWrap"><table className="dataTable accessEditorTable"><thead><tr><th>User</th><th>Role</th><th>Resource type</th><th>Resource ID</th><th>Field name</th><th>Action</th><th>Effect</th></tr></thead><tbody>{accessRows.map((r,i)=><tr key={r.user}><td><strong>{r.user_name}</strong><small className="tableSubtext">{r.user_email}</small></td><td>{r.role}</td><td>TableAsset</td><td><code>{tables.find(t=>t.id===accessTable)?.table_name||accessTable}</code></td><td>{editingAccess?<input value={r.field_name} placeholder="All fields" onChange={e=>{const a=[...accessRows];a[i]={...r,field_name:e.target.value};setAccessRows(a);setDirtyAccess(true)}}/>:(r.field_name||"All fields")}</td><td>{editingAccess?<select value={r.action} onChange={e=>{const a=[...accessRows];a[i]={...r,action:e.target.value};setAccessRows(a);setDirtyAccess(true)}}>{["READ","WRITE","UPDATE","DELETE","DDL"].map(x=><option key={x}>{x}</option>)}</select>:r.action}</td><td>{editingAccess?<select value={r.effect} onChange={e=>{const a=[...accessRows];a[i]={...r,effect:e.target.value};setAccessRows(a);setDirtyAccess(true)}}><option>ALLOW</option><option>DENY</option></select>:r.effect}</td></tr>)}</tbody></table></div>}</section></>}
 {tab==="credentials"&&<section className="card"><h2>Credentials</h2>{credentials.length?<div className="dataTableWrap"><table className="dataTable"><thead><tr><th>Source</th><th>Access</th><th>Engine</th><th>Credential</th><th>Status</th><th></th></tr></thead><tbody>{credentials.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.mode==="PRIVATE_GATEWAY"?"Private Gateway":x.mode==="EXTERNAL"?"External":"Platform"}</td><td>{x.engine}</td><td>{x.credential_location==="LOCAL"?"Local":x.credential_location==="MANAGED"?"Managed":"Not configured"}{x.connection_alias&&<small className="tableSubtext">{x.connection_alias}</small>}</td><td><span className="statusBadge">{x.configured?"Available":"Missing"}</span></td><td>{isAdmin&&x.mode==="EXTERNAL"&&<button className="button smallButton" onClick={()=>setSecretEditing(x)}>Replace</button>}</td></tr>)}</tbody></table></div>:<EmptyState title="No data sources" description="Credentials appear automatically from connected data sources."/>}{secretEditing&&<div className="card" style={{marginTop:16}}><h3>{secretEditing.name}</h3><label>Replacement credential JSON<textarea rows="6" value={secretJson} onChange={e=>setSecretJson(e.target.value)}/></label><div className="formActions"><button className="button" onClick={()=>setSecretEditing(null)}>Cancel</button><button className="button primaryButton" onClick={saveSecret}>Replace</button></div></div>}</section>}
 {tab==="changes"&&<section className="card"><div className="cardHeader"><div><h2>Platform copy history</h2><small className="tableSubtext">From the initial source snapshot to the current editable Platform copy and every publish.</small></div><select value={changeSource} onChange={e=>setChangeSource(e.target.value)}>{changeSources.map(x=><option key={x.id} value={x.id}>{x.name} · {x.mode==="PRIVATE_GATEWAY"?"Private Gateway":"External"}</option>)}</select></div>{!changeSource?<EmptyState title="No external sources" description="Connect or import an External / Private Gateway source to start its Platform-copy history."/>:<><div className="changeSummary"><div><small>Original source</small><strong>{changeSources.find(x=>x.id===changeSource)?.name}</strong></div><Icon name="transfer"/><div><small>Platform copy</small><strong>{copyEvents.length?`${copyEvents.filter(x=>!x.published).length} tracked changes`:"Waiting for initial snapshot"}</strong></div></div>{copyEvents.length?<div className="changeTimeline">{copyEvents.map((x,i)=><article className="changeEvent" key={x.id}><div className="changeRail"><span className="changeDot"/>{i<copyEvents.length-1&&<span className="changeLine"/>}</div><div className="changeBody"><div className="changeEventHeader"><strong>{x.title}</strong><span className="statusBadge">{x.kind.replaceAll("_"," ")}</span></div><p>{x.summary||"Platform copy updated."}</p><small>{new Date(x.created_at).toLocaleString()} · v{x.version}{x.actor_email?` · ${x.actor_email}`:""}</small>{x.detail&&Object.keys(x.detail).length>0&&<details><summary>Details</summary><pre className="compactCode">{JSON.stringify(x.detail,null,2)}</pre></details>}</div></article>)}</div>:<EmptyState title="No copy history yet" description="The first Platform import creates the initial snapshot automatically."/>}</>}</section>}
 {tab==="audit"&&<section className="card"><h2>Audit</h2>{audit.length?<div className="dataTableWrap"><table className="dataTable"><thead><tr><th>Date</th><th>Actor</th><th>Action</th><th>Resource</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.actor_email||x.actor||"System"}</td><td>{x.action}</td><td>{x.resource_type}<small className="tableSubtext">{x.resource_id||"—"}</small></td></tr>)}</tbody></table></div>:<EmptyState title="No audit events" description=""/>}</section>}
 </div>}
