"use client";
import {useEffect,useState} from "react";
function blankTerm(){return {variable:"",coefficient:"1"};}
function displayCoef(v){return typeof v==="object"?`$${v.parameter}`:String(v??1);}
function parseValue(v){if(String(v).startsWith("$"))return {parameter:String(v).slice(1)};return Number(v);}
export default function ExpressionForm({kind,modelId,variables,parameters,initialValue,onSubmit,onCancel,isSaving}){
 const objective=kind==="objective";
 const src=objective?initialValue?.expression:initialValue?.left_expression;
 const [f,setF]=useState({name:"",sense:objective?"MINIMIZE":"LE",constant:"0",terms:[blankTerm()],right_value:"0",enabled:true,description:""});
 useEffect(()=>setF({name:initialValue?.name||(objective?"Objective":""),sense:initialValue?.sense||(objective?"MINIMIZE":"LE"),constant:String(src?.constant??0),terms:(src?.terms?.length?src.terms:[blankTerm()]).map(t=>({variable:t.variable||"",coefficient:displayCoef(t.coefficient)})),right_value:objective?"0":displayCoef(initialValue?.right_value??0),enabled:initialValue?.enabled??true,description:initialValue?.description||""}),[initialValue,objective]);
 const set=(k,v)=>setF(o=>({...o,[k]:v})); const setTerm=(i,k,v)=>setF(o=>({...o,terms:o.terms.map((t,j)=>j===i?{...t,[k]:v}:t)}));
 function submit(e){e.preventDefault();const expression={constant:parseValue(f.constant),terms:f.terms.filter(t=>t.variable).map(t=>({variable:t.variable,coefficient:parseValue(t.coefficient)}))}; if(objective)onSubmit({model:modelId,name:f.name,sense:f.sense,expression}); else onSubmit({model:modelId,name:f.name,left_expression:expression,sense:f.sense,right_value:parseValue(f.right_value),enabled:f.enabled,description:f.description});}
 return <form className="formGrid" onSubmit={submit}>
  <label className="fieldGroup"><span>Nombre</span><input required value={f.name} onChange={e=>set("name",e.target.value)}/></label><label className="fieldGroup"><span>Sentido</span><select value={f.sense} onChange={e=>set("sense",e.target.value)}>{objective?<><option value="MINIMIZE">MINIMIZE</option><option value="MAXIMIZE">MAXIMIZE</option></>:<><option value="LE">≤</option><option value="EQ">=</option><option value="GE">≥</option></>}</select></label>
  <label className="fieldGroup"><span>Constante</span><input value={f.constant} onChange={e=>set("constant",e.target.value)} placeholder="0 o $param"/></label>{!objective&&<label className="fieldGroup"><span>Lado derecho</span><input value={f.right_value} onChange={e=>set("right_value",e.target.value)} placeholder="100 o $capacity"/></label>}
  <div className="fullWidth expressionTerms"><div className="cardHeader"><div><h3>Términos lineales</h3><p>Coeficiente × variable. El coeficiente puede ser numérico o $parámetro.</p></div><button type="button" className="button smallButton secondaryButton" onClick={()=>setF(o=>({...o,terms:[...o.terms,blankTerm()]}))}>+ Término</button></div>{f.terms.map((t,i)=><div className="expressionTerm" key={i}><select value={t.variable} onChange={e=>setTerm(i,"variable",e.target.value)}><option value="">Variable</option>{variables.map(v=><option key={v.id} value={v.name}>{v.name}</option>)}</select><span>×</span><input value={t.coefficient} onChange={e=>setTerm(i,"coefficient",e.target.value)} placeholder="1 o $cost"/><button type="button" className="button smallButton dangerButton" onClick={()=>setF(o=>({...o,terms:o.terms.filter((_,j)=>j!==i)}))}>Quitar</button></div>)}</div>
  {parameters.length>0&&<div className="fullWidth"><small>Parámetros disponibles: {parameters.map(p=>`$${p.name}`).join(", ")}</small></div>}{!objective&&<><label className="checkField"><input type="checkbox" checked={f.enabled} onChange={e=>set("enabled",e.target.checked)}/> Habilitada</label><label className="fieldGroup fullWidth"><span>Descripción</span><textarea rows="2" value={f.description} onChange={e=>set("description",e.target.value)}/></label></>}
  <div className="formActions fullWidth"><button type="button" className="button secondaryButton" onClick={onCancel}>Cancelar</button><button type="submit" className="button primaryButton" disabled={isSaving}>{isSaving?"Guardando...":"Guardar"}</button></div>
 </form>;
}