"use client";

import {useMemo,useState} from "react";

const blankVariable=()=>({name:"",description:"",variable_type:"CONTINUOUS",lower_bound:"0",upper_bound:"",baseline:""});
const blankTerm=()=>({variable:"",coefficient:"1"});
const blankConstraint=()=>({name:"",sense:"LE",right_value:"0",terms:[blankTerm()]});
const n=v=>v===""?null:Number(v);

export default function OptimizationWizard({workspaceId,onCreate,onCancel,isSaving}){
 const [step,setStep]=useState(1);
 const [f,setF]=useState({name:"",description:"",sense:"MINIMIZE",variables:[blankVariable()],objectiveTerms:[blankTerm()],constraints:[],scenarioName:"Base scenario",solverAdapter:"ORTOOLS",timeLimit:300,mipGap:""});
 const problemType=useMemo(()=>f.variables.some(v=>["INTEGER","BINARY"].includes(v.variable_type))?"MILP":"LP",[f.variables]);
 const set=(k,v)=>setF(o=>({...o,[k]:v}));
 const setVar=(i,k,v)=>setF(o=>({...o,variables:o.variables.map((x,j)=>j===i?{...x,[k]:v}:x)}));
 const setObj=(i,k,v)=>setF(o=>({...o,objectiveTerms:o.objectiveTerms.map((x,j)=>j===i?{...x,[k]:v}:x)}));
 const setConstraint=(i,k,v)=>setF(o=>({...o,constraints:o.constraints.map((x,j)=>j===i?{...x,[k]:v}:x)}));
 const setConstraintTerm=(i,t,k,v)=>setF(o=>({...o,constraints:o.constraints.map((x,j)=>j===i?{...x,terms:x.terms.map((q,z)=>z===t?{...q,[k]:v}:q)}:x)}));
 const validVars=f.variables.length>0&&f.variables.every(v=>v.name.trim());
 const validObjective=f.objectiveTerms.some(t=>t.variable&&t.coefficient!=="");
 function next(){if(step===1&&!f.name.trim())return;if(step===2&&!validVars)return;if(step===3&&!validObjective)return;setStep(s=>Math.min(6,s+1));}
 function submit(){onCreate({
   model:{workspace:workspaceId,name:f.name.trim(),description:f.description,problem_type:problemType,enabled:true},
   variables:f.variables.map(v=>({name:v.name.trim(),description:v.description,variable_type:v.variable_type,lower_bound:v.variable_type==="BINARY"?0:n(v.lower_bound)??0,upper_bound:v.variable_type==="BINARY"?1:n(v.upper_bound)})),
   objective:{name:"Objective",sense:f.sense,expression:{constant:0,terms:f.objectiveTerms.filter(t=>t.variable).map(t=>({variable:t.variable,coefficient:Number(t.coefficient)}))}},
   constraints:f.constraints.filter(c=>c.name.trim()&&c.terms.some(t=>t.variable)).map(c=>({name:c.name.trim(),description:"Created with Guided Optimization",sense:c.sense,right_value:Number(c.right_value),enabled:true,left_expression:{constant:0,terms:c.terms.filter(t=>t.variable).map(t=>({variable:t.variable,coefficient:Number(t.coefficient)}))}})),
   scenario:{name:f.scenarioName.trim()||"Base scenario",description:"Initial scenario created by Guided Optimization",parameter_values:{},baseline_values:Object.fromEntries(f.variables.filter(v=>v.baseline!=="").map(v=>[v.name,Number(v.baseline)]))},
   solver:{name:"Default solver",adapter:f.solverAdapter,solver_name:"",time_limit_seconds:Number(f.timeLimit)||300,mip_gap:f.mipGap===""?null:Number(f.mipGap),threads:null,options:{},is_default:true}
 });}
 const varNames=f.variables.filter(v=>v.name.trim()).map(v=>v.name.trim());
 return <div className="optWizard">
  <div className="optWizardSteps">{["Decision","Variables","Objective","Rules","Scenario","Review"].map((x,i)=><button type="button" key={x} className={step===i+1?"optWizardStep active":step>i+1?"optWizardStep done":"optWizardStep"} onClick={()=>i+1<step&&setStep(i+1)}><span>{step>i+1?"✓":i+1}</span>{x}</button>)}</div>
  <div className="optWizardBody">
   {step===1&&<section className="optStep"><p className="eyebrow">1 · Decision</p><h2>What decision do you want to optimize?</h2><p>Name the decision problem and choose whether a lower or higher objective is better.</p><div className="formGrid"><label className="fieldGroup"><span>Decision model name</span><input value={f.name} onChange={e=>set("name",e.target.value)} placeholder="Production allocation"/></label><label className="fieldGroup"><span>Optimization direction</span><select value={f.sense} onChange={e=>set("sense",e.target.value)}><option value="MINIMIZE">Minimize — cost, time, waste...</option><option value="MAXIMIZE">Maximize — profit, output, service...</option></select></label><label className="fieldGroup fullWidth"><span>Business description</span><textarea rows="3" value={f.description} onChange={e=>set("description",e.target.value)} placeholder="Allocate production while respecting capacity and demand."/></label></div><div className="optConceptCards"><div><strong>{f.sense==="MINIMIZE"?"Minimize":"Maximize"}</strong><span>The objective tells the solver what “better” means.</span></div><div><strong>{problemType}</strong><span>Automatically becomes MILP when a decision variable is integer or binary.</span></div></div></section>}
   {step===2&&<section className="optStep"><p className="eyebrow">2 · Decision variables</p><h2>What can the solver change?</h2><p>Each variable represents a decision. Use integer/binary only when the real decision cannot be fractional.</p><div className="optVariableList">{f.variables.map((v,i)=><div className="optVariableRow" key={i}><input aria-label="Variable name" value={v.name} onChange={e=>setVar(i,"name",e.target.value.replace(/\s+/g,"_"))} placeholder="units_A"/><select value={v.variable_type} onChange={e=>setVar(i,"variable_type",e.target.value)}><option value="CONTINUOUS">Continuous</option><option value="INTEGER">Integer</option><option value="BINARY">Binary 0/1</option></select><input type="number" step="any" value={v.lower_bound} disabled={v.variable_type==="BINARY"} onChange={e=>setVar(i,"lower_bound",e.target.value)} placeholder="Min"/><input type="number" step="any" value={v.upper_bound} disabled={v.variable_type==="BINARY"} onChange={e=>setVar(i,"upper_bound",e.target.value)} placeholder="Max (optional)"/><button type="button" className="button smallButton dangerButton" disabled={f.variables.length===1} onClick={()=>set("variables",f.variables.filter((_,j)=>j!==i))}>Remove</button></div>)}</div><button type="button" className="button secondaryButton" onClick={()=>set("variables",[...f.variables,blankVariable()])}>+ Decision variable</button></section>}
   {step===3&&<section className="optStep"><p className="eyebrow">3 · Objective</p><h2>How is the objective calculated?</h2><p>Build a linear expression. Example: cost_A × units_A + cost_B × units_B.</p><div className="optExpression"><div className="optExpressionSense">{f.sense==="MINIMIZE"?"MIN":"MAX"}</div>{f.objectiveTerms.map((t,i)=><div className="optGuidedTerm" key={i}><input type="number" step="any" value={t.coefficient} onChange={e=>setObj(i,"coefficient",e.target.value)} placeholder="Coefficient"/><span>×</span><select value={t.variable} onChange={e=>setObj(i,"variable",e.target.value)}><option value="">Decision variable</option>{varNames.map(x=><option key={x}>{x}</option>)}</select><button type="button" className="button smallButton dangerButton" disabled={f.objectiveTerms.length===1} onClick={()=>set("objectiveTerms",f.objectiveTerms.filter((_,j)=>j!==i))}>×</button></div>)}<button type="button" className="button secondaryButton smallButton" onClick={()=>set("objectiveTerms",[...f.objectiveTerms,blankTerm()])}>+ Objective term</button></div></section>}
   {step===4&&<section className="optStep"><p className="eyebrow">4 · Rules</p><h2>What rules must every solution respect?</h2><p>Add capacity, demand, balance or policy constraints. This guided mode supports numeric linear coefficients and right-hand sides.</p>{f.constraints.length===0&&<div className="optOptional"><strong>Constraints are optional</strong><span>An unconstrained model is valid, although most business decisions have at least one rule.</span></div>}<div className="optConstraintList">{f.constraints.map((c,i)=><div className="optConstraintCard" key={i}><div className="optConstraintHeader"><input value={c.name} onChange={e=>setConstraint(i,"name",e.target.value)} placeholder="Capacity"/><select value={c.sense} onChange={e=>setConstraint(i,"sense",e.target.value)}><option value="LE">≤ at most</option><option value="EQ">= exactly</option><option value="GE">≥ at least</option></select><input type="number" step="any" value={c.right_value} onChange={e=>setConstraint(i,"right_value",e.target.value)} placeholder="Limit"/><button type="button" className="button smallButton dangerButton" onClick={()=>set("constraints",f.constraints.filter((_,j)=>j!==i))}>Remove</button></div>{c.terms.map((t,z)=><div className="optGuidedTerm" key={z}><input type="number" step="any" value={t.coefficient} onChange={e=>setConstraintTerm(i,z,"coefficient",e.target.value)}/><span>×</span><select value={t.variable} onChange={e=>setConstraintTerm(i,z,"variable",e.target.value)}><option value="">Variable</option>{varNames.map(x=><option key={x}>{x}</option>)}</select><button type="button" className="button smallButton dangerButton" disabled={c.terms.length===1} onClick={()=>setConstraint(i,"terms",c.terms.filter((_,q)=>q!==z))}>×</button></div>)}<button type="button" className="linkButton" onClick={()=>setConstraint(i,"terms",[...c.terms,blankTerm()])}>+ term</button></div>)}</div><button type="button" className="button secondaryButton" onClick={()=>set("constraints",[...f.constraints,blankConstraint()])}>+ Business rule</button></section>}
   {step===5&&<section className="optStep"><p className="eyebrow">5 · Scenario & solver</p><h2>How should the first decision run?</h2><p>Create a base scenario and choose the solver adapter. Baseline values are optional and enable improvement comparison.</p><div className="formGrid"><label className="fieldGroup"><span>Scenario name</span><input value={f.scenarioName} onChange={e=>set("scenarioName",e.target.value)}/></label><label className="fieldGroup"><span>Solver adapter</span><select value={f.solverAdapter} onChange={e=>set("solverAdapter",e.target.value)}><option value="ORTOOLS">OR-Tools</option><option value="PULP">PuLP</option><option value="PYOMO">Pyomo</option></select></label><label className="fieldGroup"><span>Time limit (seconds)</span><input type="number" min="1" value={f.timeLimit} onChange={e=>set("timeLimit",e.target.value)}/></label><label className="fieldGroup"><span>MIP gap <small>(optional)</small></span><input type="number" min="0" max="1" step="any" value={f.mipGap} onChange={e=>set("mipGap",e.target.value)} placeholder="Solver default"/></label></div><h3>Current / baseline decision <small>(optional)</small></h3><div className="optBaselineGrid">{f.variables.map((v,i)=><label className="fieldGroup" key={i}><span>{v.name||`Variable ${i+1}`}</span><input type="number" step="any" value={v.baseline} onChange={e=>setVar(i,"baseline",e.target.value)} placeholder="No baseline"/></label>)}</div></section>}
   {step===6&&<section className="optStep"><p className="eyebrow">6 · Review</p><h2>Ready to create the decision model</h2><div className="optReviewGrid"><div><span>Direction</span><strong>{f.sense==="MINIMIZE"?"Minimize":"Maximize"}</strong></div><div><span>Problem</span><strong>{problemType}</strong></div><div><span>Decisions</span><strong>{f.variables.length}</strong></div><div><span>Rules</span><strong>{f.constraints.length}</strong></div><div><span>Scenario</span><strong>{f.scenarioName||"Base scenario"}</strong></div><div><span>Solver</span><strong>{f.solverAdapter}</strong></div></div><div className="optReviewEquation"><small>OBJECTIVE</small><strong>{f.sense} {f.objectiveTerms.filter(t=>t.variable).map(t=>`${t.coefficient}×${t.variable}`).join(" + ")||"—"}</strong></div><div className="mlReviewNote"><strong>What will be created?</strong><span>One OptimizationModel, its decision variables, objective, rules, a base scenario and a default SolverConfig. The backend validation remains the authority before solving.</span></div></section>}
  </div>
  <div className="mlWizardActions"><button type="button" className="button secondaryButton" onClick={step===1?onCancel:()=>setStep(s=>s-1)}>{step===1?"Cancel":"Back"}</button>{step<6?<button type="button" className="button primaryButton" onClick={next}>Continue</button>:<button type="button" className="button primaryButton" disabled={isSaving} onClick={submit}>{isSaving?"Creating decision model...":"Create decision model"}</button>}</div>
 </div>;
}
