"use client";
import {useEffect,useState} from "react";
import {listPublishPlans,createPublishPlan,listWritebackPolicies,createWritebackPolicy,deleteWritebackPolicy} from "@/lib/services/dataSources";
const arr=v=>Array.isArray(v)?v:v?.results||[];
export default function SourceLifecyclePanel({source,canManage=false,managedCopies=0}){
 const [plans,setPlans]=useState([]),[policies,setPolicies]=useState([]),[table,setTable]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){if(!source?.id)return;try{const [p,w]=await Promise.all([listPublishPlans(source.workspace,source.id),listWritebackPolicies(source.workspace,source.id)]);setPlans(arr(p));setPolicies(arr(w))}catch{}}
 useEffect(()=>{load()},[source?.id]);
 async function draftPublish(){setBusy(true);setError("");try{await createPublishPlan({workspace:source.workspace,source:source.id,name:`Publish ${source.name}`,scope:"DATA",status:"DRAFT",schema_changes:[],data_changes:{},generated_sql:""});await load()}catch(e){setError(e?.response?.data?.scope||"WRITE must be enabled before creating a data publish plan.")}finally{setBusy(false)}}
 async function addPolicy(){if(!table.trim())return;setBusy(true);setError("");try{await createWritebackPolicy({workspace:source.workspace,source:source.id,source_schema:"",source_table:table.trim(),allowed_operations:["INSERT","UPDATE"],allowed_fields:[],key_fields:[],validation_rules:{},enabled:true});setTable("");await load()}catch(e){setError(e?.response?.data?.allowed_operations||"WRITE must be enabled before writeback is allowed.")}finally{setBusy(false)}}
 return <>
  <section className="card"><div className="cardHeader"><h2>Data lifecycle</h2></div><div className="sourceWorkflowGrid"><div className="sourceWorkflowStep"><strong>Connect</strong><span>{source.mode} · {source.engine}</span></div><div className="sourceWorkflowStep"><strong>Import / Refresh</strong><span>{managedCopies} Managed {managedCopies===1?"copy":"copies"}</span></div><div className="sourceWorkflowStep"><strong>Transform</strong><span>Platform copies remain editable and independent.</span></div><div className="sourceWorkflowStep"><strong>Publish</strong><span>{plans.length} reviewed deployment {plans.length===1?"plan":"plans"}</span></div></div></section>
  <div className="sourceGovernanceGrid"><section className="card"><div className="cardHeader"><div><h2>Publish</h2></div>{canManage&&<button className="button smallButton primaryButton" disabled={busy||!source.can_write} onClick={draftPublish}>New plan</button>}</div>{error&&<div className="fieldError">{String(error)}</div>}<div className="tableWrap"><table className="dataTable"><thead><tr><th>Plan</th><th>Scope</th><th>Status</th></tr></thead><tbody>{plans.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.scope}</td><td><span className={`statusBadge status-${x.status}`}>{x.status}</span></td></tr>)}{!plans.length&&<tr><td colSpan="3">—</td></tr>}</tbody></table></div></section>
  <section className="card"><div className="cardHeader"><h2>Operational writeback</h2></div>{canManage&&<div className="compactFormRow"><label className="field"><span>Source table</span><input value={table} onChange={e=>setTable(e.target.value)}/></label><button className="button primaryButton" disabled={busy||!source.can_write||!table.trim()} onClick={addPolicy}>Add</button></div>}<div className="tableWrap"><table className="dataTable"><thead><tr><th>Table</th><th>Operations</th><th></th></tr></thead><tbody>{policies.map(x=><tr key={x.id}><td>{x.source_table}</td><td>{(x.allowed_operations||[]).join(" · ")}</td><td>{canManage&&<button className="packageRemove" onClick={async()=>{await deleteWritebackPolicy(x.id);await load()}}>×</button>}</td></tr>)}{!policies.length&&<tr><td colSpan="3">—</td></tr>}</tbody></table></div></section></div>
 </>
}
