import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces","0001_initial"),
        ("datasources","0001_initial"),
    ]
    operations=[
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id",models.BigAutoField(primary_key=True,serialize=False)),
                ("action",models.CharField(max_length=80)),
                ("resource_type",models.CharField(max_length=80)),
                ("resource_id",models.CharField(blank=True,max_length=180)),
                ("detail",models.JSONField(blank=True,default=dict)),
                ("ip_address",models.GenericIPAddressField(blank=True,null=True)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("actor",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="audit_logs",to=settings.AUTH_USER_MODEL)),
                ("workspace",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="audit_logs",to="workspaces.workspace")),
            ],
            options={"ordering":["-created_at"]},
        ),
        migrations.CreateModel(
            name="WorkspaceQuota",
            fields=[
                ("workspace",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,primary_key=True,related_name="quota",serialize=False,to="workspaces.workspace")),
                ("max_storage_mb",models.PositiveBigIntegerField(default=10240)),
                ("max_import_rows",models.PositiveBigIntegerField(default=500000)),
                ("max_export_rows",models.PositiveBigIntegerField(default=500000)),
                ("max_concurrent_jobs",models.PositiveIntegerField(default=4)),
                ("max_python_runtime_seconds",models.PositiveIntegerField(default=300)),
                ("max_optimization_seconds",models.PositiveIntegerField(default=1800)),
                ("updated_at",models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceUsage",
            fields=[
                ("workspace",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,primary_key=True,related_name="usage",serialize=False,to="workspaces.workspace")),
                ("storage_bytes",models.PositiveBigIntegerField(default=0)),
                ("import_rows",models.PositiveBigIntegerField(default=0)),
                ("export_rows",models.PositiveBigIntegerField(default=0)),
                ("executions_started",models.PositiveBigIntegerField(default=0)),
                ("updated_at",models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourcePermission",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("resource_type",models.CharField(max_length=40)),
                ("resource_id",models.CharField(blank=True,max_length=180)),
                ("field_name",models.CharField(blank=True,max_length=180)),
                ("action",models.CharField(max_length=40)),
                ("effect",models.CharField(choices=[("ALLOW","Allow"),("DENY","Deny")],default="ALLOW",max_length=10)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="resource_permissions",to=settings.AUTH_USER_MODEL)),
                ("workspace",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="resource_permissions",to="workspaces.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedSecret",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("name",models.CharField(max_length=180)),
                ("ciphertext",models.BinaryField()),
                ("key_version",models.PositiveIntegerField(default=1)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="encrypted_secrets_created",to=settings.AUTH_USER_MODEL)),
                ("data_source",models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="encrypted_secret",to="datasources.datasource")),
                ("workspace",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="encrypted_secrets",to="workspaces.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="DestructiveChangeRequest",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("action",models.CharField(max_length=80)),
                ("resource_type",models.CharField(max_length=80)),
                ("resource_id",models.CharField(max_length=180)),
                ("reason",models.TextField(blank=True)),
                ("status",models.CharField(choices=[("PENDING","Pending"),("APPROVED","Approved"),("EXECUTED","Executed"),("REJECTED","Rejected"),("EXPIRED","Expired")],default="PENDING",max_length=20)),
                ("expires_at",models.DateTimeField(blank=True,null=True)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("approved_at",models.DateTimeField(blank=True,null=True)),
                ("executed_at",models.DateTimeField(blank=True,null=True)),
                ("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="destructive_requests_approved",to=settings.AUTH_USER_MODEL)),
                ("requested_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="destructive_requests_created",to=settings.AUTH_USER_MODEL)),
                ("workspace",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="destructive_change_requests",to="workspaces.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                ("workspace",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,primary_key=True,related_name="retention_policy",serialize=False,to="workspaces.workspace")),
                ("audit_log_days",models.PositiveIntegerField(default=365)),
                ("execution_log_days",models.PositiveIntegerField(default=180)),
                ("export_artifact_days",models.PositiveIntegerField(default=30)),
                ("import_artifact_days",models.PositiveIntegerField(default=30)),
                ("updated_at",models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(model_name="auditlog",index=models.Index(fields=["workspace","created_at"],name="governance_a_workspa_14ec36_idx")),
        migrations.AddIndex(model_name="auditlog",index=models.Index(fields=["resource_type","resource_id"],name="governance_a_resourc_a2bc29_idx")),
        migrations.AddConstraint(model_name="resourcepermission",constraint=models.UniqueConstraint(fields=("workspace","user","resource_type","resource_id","field_name","action"),name="unique_resource_permission")),
        migrations.AddConstraint(model_name="encryptedsecret",constraint=models.UniqueConstraint(fields=("workspace","name"),name="unique_secret_name_per_workspace")),
    ]
