# Generated by Django 6.0.8 on 2026-09-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_datacopyevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='governance__workspa_290106_idx',
            old_name='governance_a_workspa_14ec36_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='governance__resourc_627a23_idx',
            old_name='governance_a_resourc_a2bc29_idx',
        ),
        migrations.RenameIndex(
            model_name='datacopyevent',
            new_name='governance__workspa_df6fa0_idx',
            old_name='governance_d_workspa_81bd67_idx',
        ),
    ]
