import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_model", "0002_tableasset_row_version_column"),
        ("datasources", "0001_initial"),
        ("workspaces", "0001_initial"),
        ("execution", "0003_execution_object_type_optimization"),
    ]
    operations = [
        migrations.CreateModel(
            name="OptimizationModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("problem_type", models.CharField(choices=[("LP","Linear Programming"),("MILP","Mixed Integer Linear Programming")], default="MILP", max_length=20)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="optimization_models_created", to=settings.AUTH_USER_MODEL)),
                ("data_asset", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_model_definition", to="datasources.dataasset")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="optimization_models", to="workspaces.workspace")),
            ],
            options={"ordering":["name"]},
        ),
        migrations.CreateModel(
            name="OptimizationParameter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("value_type", models.CharField(choices=[("NUMBER","Número"),("INTEGER","Entero"),("BOOLEAN","Booleano")], default="NUMBER", max_length=20)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("source_column", models.CharField(blank=True, help_text="Column name for CSV/artifact Data Assets.", max_length=180)),
                ("source_aggregation", models.CharField(blank=True, help_text="SUM/AVG/MIN/MAX/COUNT for scalar binding.", max_length=30)),
                ("description", models.TextField(blank=True)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parameters", to="optimization.optimizationmodel")),
                ("source_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_parameters", to="datasources.dataasset")),
                ("source_field", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_parameters", to="data_model.fieldasset")),
            ],
            options={"ordering":["name"]},
        ),
        migrations.CreateModel(
            name="OptimizationVariable",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("variable_type", models.CharField(choices=[("CONTINUOUS","Continua"),("INTEGER","Entera"),("BINARY","Binaria")], default="CONTINUOUS", max_length=20)),
                ("lower_bound", models.JSONField(default=0)),
                ("upper_bound", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variables", to="optimization.optimizationmodel")),
            ],
            options={"ordering":["name"]},
        ),
        migrations.CreateModel(
            name="OptimizationObjective",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="Objective", max_length=180)),
                ("sense", models.CharField(choices=[("MINIMIZE","Minimizar"),("MAXIMIZE","Maximizar")], default="MINIMIZE", max_length=20)),
                ("expression", models.JSONField(default=dict, help_text='{"constant":0,"terms":[{"variable":"x","coefficient":10}]}')),
                ("model", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="objective", to="optimization.optimizationmodel")),
            ],
        ),
        migrations.CreateModel(
            name="OptimizationConstraint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("left_expression", models.JSONField(default=dict)),
                ("sense", models.CharField(choices=[("LE","<="),("EQ","="),("GE",">=")], max_length=10)),
                ("right_value", models.JSONField(help_text="Scalar or {'parameter':'capacity'}.")),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="constraints", to="optimization.optimizationmodel")),
            ],
            options={"ordering":["name"]},
        ),
        migrations.CreateModel(
            name="SolverConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("adapter", models.CharField(choices=[("ORTOOLS","OR-Tools"),("PULP","PuLP"),("PYOMO","Pyomo")], max_length=20)),
                ("solver_name", models.CharField(blank=True, help_text="For Pyomo, e.g. highs/glpk/cbc. Optional for other adapters.", max_length=80)),
                ("time_limit_seconds", models.PositiveIntegerField(default=300)),
                ("mip_gap", models.FloatField(blank=True, null=True)),
                ("threads", models.PositiveIntegerField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="solver_configs", to="optimization.optimizationmodel")),
            ],
            options={"ordering":["name"]},
        ),
        migrations.CreateModel(
            name="OptimizationScenario",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("parameter_values", models.JSONField(blank=True, default=dict)),
                ("baseline_values", models.JSONField(blank=True, default=dict, help_text='{"x": 10, "y": 2}')),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="optimization_scenarios_created", to=settings.AUTH_USER_MODEL)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scenarios", to="optimization.optimizationmodel")),
            ],
            options={"ordering":["name"]},
        ),
        migrations.CreateModel(
            name="OptimizationRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("execution_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(choices=[("QUEUED","En cola"),("RUNNING","Ejecutando"),("OPTIMAL","Óptima"),("FEASIBLE","Factible"),("INFEASIBLE","Infactible"),("UNBOUNDED","No acotada"),("FAILED","Fallida"),("CANCELLED","Cancelada")], default="QUEUED", max_length=20)),
                ("objective_value", models.FloatField(blank=True, null=True)),
                ("best_bound", models.FloatField(blank=True, null=True)),
                ("gap", models.FloatField(blank=True, null=True)),
                ("solve_time_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("variable_values", models.JSONField(blank=True, default=dict)),
                ("baseline_objective_value", models.FloatField(blank=True, null=True)),
                ("baseline_feasible", models.BooleanField(blank=True, null=True)),
                ("improvement_absolute", models.FloatField(blank=True, null=True)),
                ("improvement_percent", models.FloatField(blank=True, null=True)),
                ("input_asset_versions", models.JSONField(blank=True, default=dict)),
                ("solver_metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="optimization.optimizationmodel")),
                ("scenario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="optimization.optimizationscenario")),
                ("solver_config", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="optimization.solverconfig")),
            ],
            options={"ordering":["-created_at"]},
        ),
        migrations.CreateModel(
            name="OptimizationSolutionAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("artifact_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_asset", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="optimization_solution", to="datasources.dataasset")),
                ("run", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="solution_asset", to="optimization.optimizationrun")),
            ],
        ),
        migrations.AddConstraint(model_name="optimizationmodel", constraint=models.UniqueConstraint(fields=("workspace","name"), name="unique_optimization_model_name_per_workspace")),
        migrations.AddConstraint(model_name="optimizationparameter", constraint=models.UniqueConstraint(fields=("model","name"), name="unique_optimization_parameter_name")),
        migrations.AddConstraint(model_name="optimizationvariable", constraint=models.UniqueConstraint(fields=("model","name"), name="unique_optimization_variable_name")),
        migrations.AddConstraint(model_name="optimizationconstraint", constraint=models.UniqueConstraint(fields=("model","name"), name="unique_optimization_constraint_name")),
        migrations.AddConstraint(model_name="solverconfig", constraint=models.UniqueConstraint(fields=("model","name"), name="unique_solver_config_name_per_model")),
        migrations.AddConstraint(model_name="optimizationscenario", constraint=models.UniqueConstraint(fields=("model","name"), name="unique_optimization_scenario_name")),
    ]
