# Generated by Django 6.0.8 on 2026-08-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationvariable',
            name='lower_bound',
            field=models.JSONField(default=int),
        ),
    ]
