import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_model", "0002_tableasset_row_version_column"),
        ("datasources", "0001_initial"),
        ("workspaces", "0001_initial"),
        ("execution", "0002_execution_object_types_phase8"),
    ]
    operations = [
        migrations.CreateModel(
            name="DatasetDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("filter_config", models.JSONField(blank=True, default=list)),
                ("sample_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="datasets_created", to=settings.AUTH_USER_MODEL)),
                ("source_table", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dataset_definitions", to="data_model.tableasset")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to="workspaces.workspace")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="PythonTransformation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("code", models.TextField(help_text="Use table('alias') y save_table(dataframe).")),
                ("output_name", models.CharField(max_length=180)),
                ("allowed_packages", models.JSONField(blank=True, default=list)),
                ("timeout_seconds", models.PositiveIntegerField(default=300)),
                ("memory_limit_mb", models.PositiveIntegerField(default=1024)),
                ("max_input_rows", models.PositiveIntegerField(default=100000)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="python_transformations_created", to=settings.AUTH_USER_MODEL)),
                ("output_asset", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="producer_python_transformation", to="datasources.dataasset")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="python_transformations", to="workspaces.workspace")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="PythonTransformationInput",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=80)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="python_transformation_inputs", to="datasources.dataasset")),
                ("transformation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inputs", to="data_science.pythontransformation")),
            ],
        ),
        migrations.CreateModel(
            name="ModelDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("task_type", models.CharField(choices=[("CLASSIFICATION","Clasificación"),("REGRESSION","Regresión")], max_length=30)),
                ("algorithm", models.CharField(choices=[("LOGISTIC_REGRESSION","Logistic Regression"),("RANDOM_FOREST_CLASSIFIER","Random Forest Classifier"),("LINEAR_REGRESSION","Linear Regression"),("RANDOM_FOREST_REGRESSOR","Random Forest Regressor")], max_length=40)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("test_size", models.FloatField(default=0.2)),
                ("random_state", models.IntegerField(default=42)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ml_models_created", to=settings.AUTH_USER_MODEL)),
                ("data_asset", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ml_model_definition", to="datasources.dataasset")),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="models", to="data_science.datasetdefinition")),
                ("features", models.ManyToManyField(related_name="ml_feature_models", to="data_model.fieldasset")),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ml_target_models", to="data_model.fieldasset")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ml_models", to="workspaces.workspace")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ModelRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("execution_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(choices=[("QUEUED","En cola"),("RUNNING","Ejecutando"),("SUCCESS","Exitosa"),("FAILED","Fallida"),("CANCELLED","Cancelada")], default="QUEUED", max_length=20)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("parameters_snapshot", models.JSONField(blank=True, default=dict)),
                ("input_asset_versions", models.JSONField(blank=True, default=dict)),
                ("row_count", models.PositiveBigIntegerField(default=0)),
                ("train_row_count", models.PositiveBigIntegerField(default=0)),
                ("test_row_count", models.PositiveBigIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="data_science.modeldefinition")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("artifact_path", models.TextField()),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("feature_names", models.JSONField(blank=True, default=list)),
                ("target_name", models.CharField(max_length=180)),
                ("algorithm", models.CharField(max_length=80)),
                ("sklearn_version", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="data_science.modeldefinition")),
                ("run", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="model_version", to="data_science.modelrun")),
            ],
            options={"ordering": ["-version"]},
        ),
        migrations.CreateModel(
            name="PredictionAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("artifact_path", models.TextField()),
                ("row_count", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_asset", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="prediction_definition", to="datasources.dataasset")),
                ("model_version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prediction_assets", to="data_science.modelversion")),
                ("source_dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="predictions", to="data_science.datasetdefinition")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="datasetdefinition", constraint=models.UniqueConstraint(fields=("workspace","name"), name="unique_dataset_name_per_workspace")),
        migrations.AddConstraint(model_name="pythontransformation", constraint=models.UniqueConstraint(fields=("workspace","name"), name="unique_python_transformation_name_per_workspace")),
        migrations.AddConstraint(model_name="pythontransformationinput", constraint=models.UniqueConstraint(fields=("transformation","alias"), name="unique_python_input_alias")),
        migrations.AddConstraint(model_name="pythontransformationinput", constraint=models.UniqueConstraint(fields=("transformation","asset"), name="unique_python_input_asset")),
        migrations.AddConstraint(model_name="modeldefinition", constraint=models.UniqueConstraint(fields=("workspace","name"), name="unique_ml_model_name_per_workspace")),
        migrations.AddConstraint(model_name="modelversion", constraint=models.UniqueConstraint(fields=("model","version"), name="unique_model_version_number")),
    ]
