import hashlib
import re
from dataclasses import dataclass

from django.db import connection, transaction
from django.utils.text import slugify

from datasources.models import DataAsset, DataSource

from .managed_types import LOGICAL_TYPE_SQL
from .models import FieldAsset, RelationAsset, TableAsset


RESERVED_INTERNAL_COLUMNS = {"__row_version"}


def workspace_schema_name(workspace_id) -> str:
    compact = str(workspace_id).replace("-", "")
    return f"ws_{compact[:24]}"


def quote(identifier: str) -> str:
    return connection.ops.quote_name(identifier)


def build_sql_type(field: dict) -> str:
    logical_type = field["logical_type"]

    if logical_type == "STRING":
        return f"varchar({int(field.get('max_length') or 255)})"

    if logical_type == "DECIMAL":
        precision = int(field.get("numeric_precision") or 18)
        scale = int(field.get("numeric_scale") or 2)
        return f"numeric({precision},{scale})"

    if field.get("is_identity"):
        if logical_type == "INTEGER":
            return "integer GENERATED BY DEFAULT AS IDENTITY"
        if logical_type == "BIGINT":
            return "bigint GENERATED BY DEFAULT AS IDENTITY"

    return LOGICAL_TYPE_SQL[logical_type]


def sql_default_clause(field: dict):
    if "default" not in field:
        return "", []

    value = field["default"]
    if value is None:
        return " DEFAULT NULL", []

    return " DEFAULT %s", [value]


def ensure_managed_datasource(workspace, user):
    source = DataSource.objects.filter(
        workspace=workspace,
        mode=DataSource.Mode.MANAGED,
        engine=DataSource.Engine.PLATFORM_POSTGRES,
    ).order_by("created_at").first()
    if source is None:
        source = DataSource.objects.create(
            workspace=workspace,
            mode=DataSource.Mode.MANAGED,
            engine=DataSource.Engine.PLATFORM_POSTGRES,
            name="Managed Database",
            status=DataSource.Status.ACTIVE,
            can_read=True,
            can_write=True,
            can_ddl=True,
            connection_metadata={
                "strategy": "workspace_schema",
                "schema": workspace_schema_name(workspace.id),
            },
            created_by=user,
        )

    desired_metadata = dict(source.connection_metadata or {})
    desired_metadata.setdefault("strategy", "workspace_schema")
    desired_metadata.setdefault("schema", workspace_schema_name(workspace.id))

    if not source.can_read or not source.can_write or not source.can_ddl or source.connection_metadata != desired_metadata:
        source.can_read = True
        source.can_write = True
        source.can_ddl = True
        source.status = DataSource.Status.ACTIVE
        source.connection_metadata = desired_metadata
        source.save(
            update_fields=["can_read", "can_write", "can_ddl", "status", "connection_metadata", "updated_at"]
        )

    return source


@dataclass(slots=True)
class ManagedTableBuildResult:
    table_asset: TableAsset
    created_schema: str

    def to_dict(self):
        return {
            "table_asset_id": str(self.table_asset.id),
            "data_asset_id": str(self.table_asset.data_asset_id),
            "schema": self.table_asset.schema_name,
            "table": self.table_asset.table_name,
        }


@transaction.atomic
def create_managed_table(*, workspace, name, display_name, fields, primary_key, foreign_keys, user):
    if name in RESERVED_INTERNAL_COLUMNS:
        raise ValueError("Nombre de tabla reservado.")

    for field in fields:
        if field["name"] in RESERVED_INTERNAL_COLUMNS:
            raise ValueError(f"El campo {field['name']} está reservado por la plataforma.")

    data_source = ensure_managed_datasource(workspace, user)
    schema_name = workspace_schema_name(workspace.id)

    if TableAsset.objects.filter(
        data_source=data_source,
        schema_name=schema_name,
        table_name=name,
    ).exists():
        raise ValueError("Ya existe una tabla con ese nombre en el workspace.")

    column_sql = []
    params = []

    for field in fields:
        parts = [quote(field["name"]), build_sql_type(field)]

        if not field.get("nullable", True):
            parts.append("NOT NULL")

        if field.get("unique"):
            parts.append("UNIQUE")

        default_clause, default_params = sql_default_clause(field)
        if default_clause:
            parts.append(default_clause.strip())
            params.extend(default_params)

        column_sql.append(" ".join(parts))

    # Technical concurrency column.
    column_sql.append(f'{quote("__row_version")} bigint NOT NULL DEFAULT 1')

    if primary_key:
        pk = ", ".join(quote(name) for name in primary_key)
        column_sql.append(f"PRIMARY KEY ({pk})")

    fk_names = []
    for index, fk in enumerate(foreign_keys or [], start=1):
        target = fk["target_table_asset"]
        constraint_name = f"fk_{name}_{index}"
        fk_names.append(constraint_name)

        source_columns = ", ".join(quote(col) for col in fk["columns"])
        target_columns = ", ".join(quote(col) for col in fk["target_columns"])

        column_sql.append(
            f"CONSTRAINT {quote(constraint_name)} "
            f"FOREIGN KEY ({source_columns}) "
            f"REFERENCES {quote(target.schema_name)}.{quote(target.table_name)} "
            f"({target_columns}) "
            f"ON DELETE {fk['on_delete']}"
        )

    ddl = (
        f"CREATE TABLE {quote(schema_name)}.{quote(name)} ("
        + ", ".join(column_sql)
        + ")"
    )

    with connection.cursor() as cursor:
        cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {quote(schema_name)}")
        cursor.execute(ddl, params)

    logical_name = display_name.strip() if display_name else name

    data_asset = DataAsset.objects.create(
        workspace=workspace,
        data_source=data_source,
        name=logical_name,
        asset_type=DataAsset.AssetType.TABLE,
        status=DataAsset.Status.ACTIVE,
        physical_schema=schema_name,
        physical_name=name,
        metadata={
            "catalog_origin": "managed_builder",
            "managed": True,
        },
        created_by=user,
    )

    table_asset = TableAsset.objects.create(
        data_asset=data_asset,
        data_source=data_source,
        schema_name=schema_name,
        table_name=name,
        technical_name=name,
        object_type=TableAsset.ObjectType.TABLE,
        primary_key_columns=list(primary_key or []),
        row_version_column="__row_version",
    )

    for position, field in enumerate(fields, start=1):
        FieldAsset.objects.create(
            table_asset=table_asset,
            name=field["name"],
            logical_type=field["logical_type"],
            native_type=build_sql_type(field),
            ordinal_position=position,
            nullable=field.get("nullable", True),
            default_value="" if "default" not in field else str(field.get("default")),
            max_length=field.get("max_length"),
            numeric_precision=field.get("numeric_precision"),
            numeric_scale=field.get("numeric_scale"),
            is_primary_key=field["name"] in (primary_key or []),
            is_identity=field.get("is_identity", False),
            origin=FieldAsset.Origin.PLATFORM,
        )

    for index, fk in enumerate(foreign_keys or [], start=1):
        target = fk["target_table_asset"]
        RelationAsset.objects.create(
            data_source=data_source,
            name=f"fk_{name}_{index}",
            source_table=table_asset,
            target_table=target,
            source_columns=list(fk["columns"]),
            target_columns=list(fk["target_columns"]),
        )

    return ManagedTableBuildResult(
        table_asset=table_asset,
        created_schema=schema_name,
    )


@transaction.atomic
def delete_managed_table(table_asset: TableAsset):
    if table_asset.data_source.mode != DataSource.Mode.MANAGED:
        raise ValueError("Solo se pueden eliminar físicamente tablas MANAGED.")

    with connection.cursor() as cursor:
        cursor.execute(
            f"DROP TABLE {quote(table_asset.schema_name)}."
            f"{quote(table_asset.table_name)}"
        )

    data_asset = table_asset.data_asset
    table_asset.delete()
    data_asset.delete()
