"use client";
import useExecutionEvents from "@/components/ai/useExecutionEvents";
const LABELS={accuracy:"Accuracy",precision:"Precision",recall:"Recall",f1_score:"F1 Score",f1_weighted:"F1 Weighted",roc_auc:"ROC-AUC",pr_auc:"PR-AUC",log_loss:"Log Loss",mae:"MAE",rmse:"RMSE",mse:"MSE",r2:"R²"};
function fmt(v){return v===null||v===undefined?"—":typeof v==="number"?v.toLocaleString(undefined,{maximumFractionDigits:4}):String(v)}
function pct(v){return typeof v==="number"&&v>=0&&v<=1?`${(v*100).toFixed(1)}%`:fmt(v)}
function seriesFrom(events){const map={};for(const e of events){if(e.event_type==="METRIC_REPORTED"&&e.payload?.step!==undefined){const n=e.payload.name;(map[n]??=[]).push({x:Number(e.payload.step),y:Number(e.payload.value)});}if(e.event_type==="ML_EPOCH_COMPLETED")for(const [n,v] of Object.entries(e.payload?.metrics||{})){if(typeof v==="number")(map[n]??=[]).push({x:Number(e.payload.epoch),y:v});}}return map;}
function Line({points=[],empty="No data available."}){if(points.length<2)return <div className="mlEmpty">{empty}</div>;const ys=points.map(p=>Number(p.y)).filter(Number.isFinite);if(!ys.length)return <div className="mlEmpty">{empty}</div>;const lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1;const shown=points.slice(-160),ps=shown.map((p,i)=>`${18+i*(484/Math.max(1,shown.length-1))},${154-((Number(p.y)-lo)/span)*124}`).join(" ");return <svg className="mlLineChart" viewBox="0 0 520 175"><line x1="18" y1="154" x2="502" y2="154" className="mlAxis"/><polyline points={ps} fill="none" stroke="currentColor" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/></svg>}
function Confusion({matrix=[],labels=[]}){if(!Array.isArray(matrix)||!matrix.length)return <div className="mlEmpty">Confusion matrix is not available for this run.</div>;const max=Math.max(1,...matrix.flat().map(Number));return <div className="mlConfusion" style={{gridTemplateColumns:`minmax(90px,.7fr) repeat(${Math.max(1,labels.length)},minmax(70px,1fr))`}}><div className="mlConfusionCorner">Actual ↓ / Predicted →</div>{labels.map((l,i)=><div className="mlConfusionLabel" key={`h${i}`}>{l}</div>)}{matrix.map((row,r)=><div className="mlConfusionRow" key={r}><div className="mlConfusionLabel">{labels[r]??r}</div>{row.map((v,c)=><div key={c} className="mlConfusionCell" style={{"--strength":Math.max(.06,Number(v)/max)}}><strong>{fmt(v)}</strong><span>{labels[c]??c}</span></div>)}</div>)}</div>}
function ClassificationReport({report={}}){const rows=Object.entries(report||{}).filter(([,v])=>v&&typeof v==="object"&&"precision" in v);if(!rows.length)return <div className="mlEmpty">Classification report is not available for this run.</div>;return <div className="mlReportTable"><div className="mlReportHead"><span>Class</span><span>Precision</span><span>Recall</span><span>F1</span><span>Support</span></div>{rows.map(([name,v])=><div className="mlReportRow" key={name}><strong>{name}</strong><span>{fmt(v.precision)}</span><span>{fmt(v.recall)}</span><span>{fmt(v["f1-score"])}</span><span>{fmt(v.support)}</span></div>)}</div>}
function Distribution({data={}}){const rows=Object.entries(data||{}),max=Math.max(1,...rows.map(([,v])=>Number(v)));if(!rows.length)return <div className="mlEmpty">Class distribution is not available.</div>;return <div className="mlBars">{rows.map(([k,v])=><div key={k}><span>{k}</span><i><b style={{width:`${Number(v)/max*100}%`}}/></i><strong>{fmt(v)}</strong></div>)}</div>}
function duration(latest,execution){if(execution?.duration_ms)return `${fmt(execution.duration_ms)} ms`;if(latest?.started_at&&latest?.finished_at)return `${((new Date(latest.finished_at)-new Date(latest.started_at))/1000).toFixed(2)} s`;return "—"}
export default function MLReport({model,runs=[],versions=[],execution=null,onCancel=null}){const latest=runs[0],latestVersion=versions[0];const {events}=useExecutionEvents(execution?.id);const liveSeries=seriesFrom(events);const metrics={...(latestVersion?.metrics||{}),...(latest?.metrics||{})};for(const e of events)if(e.event_type==="METRIC_REPORTED"&&e.payload?.scope==="evaluation")metrics[e.payload.name]=e.payload.value;const classification=model.task_type==="CLASSIFICATION";const headline=(classification?["accuracy","precision","recall","f1_score","roc_auc","pr_auc"]:["mae","rmse","r2","mse"]).filter(k=>typeof metrics[k]==="number");const labels=metrics.class_labels?.length?metrics.class_labels:(metrics.confusion_matrix||[]).map((_,i)=>String(i));const seriesNames=Object.keys(liveSeries);return <div className="mlWorkspaceReport">
 <header className="mlHero"><div><div className="mlEyebrow">Data Science / Model report</div><h1>{model.name}</h1><div className="mlHeroTags"><span>{model.algorithm?.replaceAll("_"," ")}</span><span>{model.task_type?.replaceAll("_"," ")}</span><span className={`mlStatus ${String(latest?.status||"not-run").toLowerCase()}`}>{latest?.status||"NOT RUN"}</span></div></div><div className="mlHeroMeta"><div><span>Latest run</span><strong>{latest?.created_at?new Date(latest.created_at).toLocaleString():"—"}</strong></div><div><span>Version</span><strong>{latestVersion?`v${latestVersion.version}`:"—"}</strong></div>{onCancel&&["QUEUED","RUNNING"].includes(execution?.status)&&<button type="button" className="secondaryButton" onClick={onCancel}>Cancel run</button>}</div></header>
 <section className="mlMetricStrip">{headline.length?headline.map(k=><article key={k}><span>{LABELS[k]||k.replaceAll("_"," ")}</span><strong>{k==="log_loss"?fmt(metrics[k]):pct(metrics[k])}</strong></article>):<div className="mlEmpty">Evaluation metrics will appear after a successful run or a model is registered from Code.</div>}</section>
 <div className="mlReportGrid"><main>
   <section className="mlPanel"><div className="mlPanelTitle"><div><span>Evaluation</span><h2>Evaluation profile</h2></div><small>{classification?"Classification diagnostics":"Regression diagnostics"}</small></div>{classification ? (<div className="mlTwoCols"><div><h3>Confusion matrix</h3><Confusion matrix={metrics.confusion_matrix} labels={labels}/></div><div><h3>Class distribution</h3><Distribution data={metrics.class_distribution}/></div></div>) : (<div className="mlTwoCols"><div><h3>Actual vs predicted</h3><div className="mlEmpty">{metrics.actual_vs_predicted?.length ? `${metrics.actual_vs_predicted.length} evaluation points captured.` : "No prediction profile captured."}</div></div><div><h3>Residual profile</h3><div className="mlEmpty">{metrics.residuals?.length ? `${metrics.residuals.length} residuals captured.` : "No residual profile captured."}</div></div></div>)}</section>
  {classification&&<section className="mlPanel"><div className="mlPanelTitle"><div><span>Per-class quality</span><h2>Classification report</h2></div></div><ClassificationReport report={metrics.classification_report}/></section>}
  {classification&&<section className="mlPanel"><div className="mlPanelTitle"><div><span>Threshold behavior</span><h2>ROC & Precision–Recall</h2></div></div><div className="mlTwoCols"><div className="mlChartCard"><h3>ROC curve <em>{typeof metrics.roc_auc==="number"?`AUC ${metrics.roc_auc.toFixed(3)}`:""}</em></h3><Line points={metrics.roc_curve||[]} empty="ROC curve requires probability or decision scores."/></div><div className="mlChartCard"><h3>Precision–Recall <em>{typeof metrics.pr_auc==="number"?`AP ${metrics.pr_auc.toFixed(3)}`:""}</em></h3><Line points={metrics.precision_recall_curve||[]} empty="Precision–Recall curve requires probability scores."/></div></div></section>}
  <section className="mlPanel"><div className="mlPanelTitle"><div><span>Training</span><h2>Runtime training series</h2></div><small>{seriesNames.length?`${seriesNames.length} series`:"Non-iterative estimator"}</small></div>{seriesNames.length?<div className="mlTwoCols">{seriesNames.slice(0,4).map(n=><div className="mlChartCard" key={n}><h3>{n.replaceAll("_"," ")}</h3><Line points={liveSeries[n]}/></div>)}</div>:<div className="mlEmpty mlEmptyLarge">This estimator did not emit iterative epoch/metric history. Runtime and evaluation results are still recorded below.</div>}</section>
 </main><aside>
  <section className="mlSidePanel"><h3>Run profile</h3><dl><div><dt>Rows</dt><dd>{fmt(latest?.row_count)}</dd></div><div><dt>Train</dt><dd>{fmt(latest?.train_row_count)}</dd></div><div><dt>Test</dt><dd>{fmt(latest?.test_row_count)}</dd></div><div><dt>Features</dt><dd>{latestVersion?.feature_names?.length??"—"}</dd></div><div><dt>Duration</dt><dd>{duration(latest,execution)}</dd></div><div><dt>Versions</dt><dd>{versions.length}</dd></div></dl></section>
  <section className="mlSidePanel"><h3>Model provenance</h3><dl><div><dt>Target</dt><dd>{latestVersion?.target_name||"—"}</dd></div><div><dt>Runtime</dt><dd>{metrics.runtime?.source||"Managed training"}</dd></div><div><dt>Library</dt><dd>{latestVersion?.sklearn_version?`scikit-learn ${latestVersion.sklearn_version}`:(metrics.runtime?.python_module||"—")}</dd></div><div><dt>Execution</dt><dd className="mlMono">{execution?.id?String(execution.id).slice(0,12)+"…":"—"}</dd></div></dl></section>
  <section className="mlSidePanel"><h3>Run history</h3><div className="mlRunList">{runs.slice(0,6).map((r,i)=><div key={r.id}><span>#{runs.length-i}</span><div><strong>{r.status}</strong><small>{r.created_at?new Date(r.created_at).toLocaleString():"—"}</small></div></div>)}</div></section>
 </aside></div>
 </div>}
