"use client";
import useExecutionEvents from "@/components/ai/useExecutionEvents";
function fmt(v){return v===null||v===undefined?"—":typeof v==="number"?v.toLocaleString(undefined,{maximumFractionDigits:4}):String(v)}
function metricEntries(metrics={}){return Object.entries(metrics||{}).filter(([,v])=>typeof v==="number"&&Number.isFinite(v));}
function seriesFrom(events){const map={};for(const e of events){if(e.event_type==="METRIC_REPORTED"&&e.payload?.step!==undefined){const n=e.payload.name;(map[n]??=[]).push({x:Number(e.payload.step),y:Number(e.payload.value)});}if(e.event_type==="ML_EPOCH_COMPLETED")for(const [n,v] of Object.entries(e.payload?.metrics||{})){if(typeof v==="number")(map[n]??=[]).push({x:Number(e.payload.epoch),y:v});}}return map;}
function Line({points=[]}){if(points.length<2)return <div className="reportEmpty">Waiting for runtime series.</div>;const ys=points.map(p=>p.y),lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1;const ps=points.slice(-120).map((p,i)=>`${12+i*(396/Math.max(1,Math.min(points.length,120)-1))},${128-((p.y-lo)/span)*104}`).join(" ");return <svg className="reportChart" viewBox="0 0 420 145"><polyline points={ps} fill="none" stroke="currentColor" strokeWidth="2.5"/></svg>}
export default function MLReport({model,runs=[],versions=[],execution=null}){const latest=runs[0];const {events}=useExecutionEvents(execution?.id);const series=seriesFrom(events);const metrics={...(latest?.metrics||{})};for(const e of events)if(e.event_type==="METRIC_REPORTED"&&e.payload?.scope==="evaluation")metrics[e.payload.name]=e.payload.value;const names=Object.keys(series);return <div className="analysisReport">
  <section className="reportLead"><div><span>Machine Learning report</span><h1>{model.name}</h1><p>{model.algorithm?.replaceAll("_"," ")} · {model.task_type?.replaceAll("_"," ")} · {latest?.status||"NOT RUN"}</p></div><div className="reportLeadMeta"><span>Latest run</span><strong>{latest?.created_at?new Date(latest.created_at).toLocaleString():"—"}</strong></div></section>
  <section className="reportSection"><h2>Performance</h2><div className="reportMetrics">{metricEntries(metrics).length?metricEntries(metrics).map(([k,v])=><div key={k}><span>{k.replaceAll("_"," ")}</span><strong>{fmt(v)}</strong></div>):<p className="reportEmpty">Evaluation metrics will appear after a successful execution.</p>}</div></section>
  <section className="reportSection"><h2>Training behavior</h2><div className="reportVisualGrid">{names.length?names.slice(0,4).map(n=><div className="reportVisual" key={n}><header><strong>{n.replaceAll("_"," ")}</strong><span>{series[n].length} points</span></header><Line points={series[n]}/></div>):<div className="reportVisual wide"><header><strong>Runtime training series</strong></header><div className="reportEmpty">The report fills automatically when a runtime adapter emits epoch or metric events.</div></div>}</div></section>
  <section className="reportSection"><h2>Model behavior</h2><div className="reportVisualGrid"><div className="reportVisual"><header><strong>Decision surface / projection</strong></header><div className="behaviorSurface"><i/><i/><i/><i/><i/></div><small>Shown from adapter-generated prediction surfaces when the model/problem supports a meaningful 2D projection.</small></div><div className="reportVisual"><header><strong>Evaluation profile</strong></header><div className="reportEmpty">Classification: ROC/confusion matrix · Regression: residuals/actual vs predicted · Clustering: projection/silhouette. The runtime profile selects compatible visuals.</div></div></div></section>
  <section className="reportSection"><h2>Outputs & provenance</h2><div className="reportTable"><div><span>Versions</span><strong>{versions.length}</strong></div><div><span>Rows</span><strong>{fmt(latest?.row_count)}</strong></div><div><span>Train / test</span><strong>{fmt(latest?.train_row_count)} / {fmt(latest?.test_row_count)}</strong></div><div><span>Execution</span><strong>{execution?.id||"—"}</strong></div><div><span>Duration</span><strong>{execution?.duration_ms?`${fmt(execution.duration_ms)} ms`:"—"}</strong></div><div><span>Live events</span><strong>{events.length}</strong></div></div></section>
</div>}
