"use client";
import useExecutionEvents from "@/components/ai/useExecutionEvents";
function fmt(v){return v===null||v===undefined?"—":typeof v==="number"?v.toLocaleString(undefined,{maximumFractionDigits:4}):String(v)}
function expr(e){if(!e)return "0";const p=[];if(e.constant)p.push(String(e.constant));for(const t of e.terms||[])p.push(`${typeof t.coefficient==="object"?t.coefficient.parameter:t.coefficient??1}·${t.variable}`);return p.join(" + ")||"0"}
function sense(v){return v==="LE"?"≤":v==="GE"?"≥":"="}
function Trace({points}){if(points.length<2)return <div className="reportEmpty">Waiting for solver progress events.</div>;const ys=points.map(p=>p.y),lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1;const ps=points.slice(-160).map((p,i)=>`${12+i*(396/Math.max(1,Math.min(points.length,160)-1))},${128-((p.y-lo)/span)*104}`).join(" ");return <svg className="reportChart" viewBox="0 0 420 145"><polyline points={ps} fill="none" stroke="currentColor" strokeWidth="2.5"/></svg>}
export default function OptimizationReport({model,objective,constraints=[],runs=[],solutions=[],execution=null,onCancel=null}){const latest=runs[0];const {events}=useExecutionEvents(execution?.id);const progress=events.filter(e=>e.event_type==="OPTIMIZATION_PROGRESS");const incumbent=progress.map((e,i)=>({x:e.payload?.iteration??i,y:Number(e.payload?.incumbent)})).filter(p=>Number.isFinite(p.y));const bound=progress.map((e,i)=>({x:e.payload?.iteration??i,y:Number(e.payload?.best_bound)})).filter(p=>Number.isFinite(p.y));return <div className="analysisReport">
<section className="reportLead"><div><span>Optimization report</span><h1>{model.name}</h1><p>{model.problem_type} · {latest?.status||"NOT RUN"}</p></div><div className="reportLeadMeta"><span>Latest run</span><strong>{latest?.created_at?new Date(latest.created_at).toLocaleString():"—"}</strong>{onCancel&&["QUEUED","RUNNING"].includes(execution?.status)&&<button type="button" className="secondaryButton" onClick={onCancel}>Cancel run</button>}</div></section>
<section className="reportSection"><h2>Solution</h2><div className="reportMetrics"><div><span>Status</span><strong>{latest?.status||"—"}</strong></div><div><span>Objective</span><strong>{fmt(latest?.objective_value)}</strong></div><div><span>Best bound / baseline</span><strong>{fmt(progress.at(-1)?.payload?.best_bound??latest?.baseline_objective_value)}</strong></div><div><span>Gap</span><strong>{fmt(progress.at(-1)?.payload?.gap??latest?.gap)}</strong></div><div><span>Solve time</span><strong>{latest?.solve_time_ms?`${fmt(latest.solve_time_ms)} ms`:"—"}</strong></div></div></section>
<section className="reportSection"><h2>Solution search</h2><div className="reportVisualGrid"><div className="reportVisual"><header><strong>Incumbent objective</strong><span>{incumbent.length} points</span></header><Trace points={incumbent}/></div><div className="reportVisual"><header><strong>Best bound</strong><span>{bound.length} points</span></header><Trace points={bound}/></div></div></section>
<section className="reportSection"><h2>Mathematical model</h2>{objective?<div className="mathReport"><span>Objective · {objective.sense}</span><strong>{objective.sense==="MAXIMIZE"?"max":"min"} &nbsp; {expr(objective.expression)}</strong></div>:<p className="reportEmpty">Objective metadata will be extracted by the solver adapter.</p>}<div className="mathRows">{constraints.map(c=><div key={c.id}><span>{c.name}</span><strong>{expr(c.left_expression)} {sense(c.sense)} {typeof c.right_value==="object"?c.right_value.parameter:fmt(c.right_value)}</strong></div>)}</div></section>
<section className="reportSection"><h2>Solution outputs</h2><div className="reportTable"><div><span>Solution artifacts</span><strong>{solutions.length}</strong></div><div><span>Decision values</span><strong>{Object.keys(latest?.variable_values||{}).length}</strong></div><div><span>Improvement</span><strong>{latest?.improvement_percent==null?"—":`${fmt(latest.improvement_percent)}%`}</strong></div><div><span>Execution</span><strong>{execution?.id||"—"}</strong></div><div><span>Live events</span><strong>{events.length}</strong></div></div></section>
</div>}
