"use client";
import {useEffect,useMemo,useState} from "react";
import {createPlatformField,saveFieldContentRule} from "@/lib/services/dataModel";
import {getApiErrorMessage} from "@/lib/utils/errors";
import Alert from "@/components/ui/Alert";

const MODES=["MANUAL","DAX","SQL","PYTHON"];
const TYPES=["STRING","INTEGER","BIGINT","DECIMAL","FLOAT","BOOLEAN","DATE","DATETIME","TEXT"];
export default function FieldRulesManager({tables=[],sources=[],initialTableId,onClose,onChanged}){
 const [tableId,setTableId]=useState(initialTableId||tables[0]?.id||""),[drafts,setDrafts]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[addOpen,setAddOpen]=useState(false),[newField,setNewField]=useState({name:"",logical_type:"STRING",nullable:true});
 const table=useMemo(()=>tables.find(t=>String(t.id)===String(tableId)),[tables,tableId]);const source=sources.find(s=>s.id===table?.data_source);
 useEffect(()=>{if(!table)return;const next={};(table.fields||[]).forEach(f=>next[f.id]={mode:f.content_rule?.mode||"MANUAL",expression:f.content_rule?.expression||""});setDrafts(next)},[table]);
 function editable(f){return source?.mode==="MANAGED"||f.origin==="PLATFORM"||f.editable_in_platform}
 function patch(id,p){setDrafts(d=>({...d,[id]:{...(d[id]||{}),...p}}))}
 async function save(f){setBusy(true);setError("");try{const d=drafts[f.id]||{mode:"MANUAL",expression:""};await saveFieldContentRule({field:f.id,mode:d.mode,expression:d.mode==="MANUAL"?"":d.expression,dependencies:[]},f.content_rule?.id||null);await onChanged?.()}catch(e){setError(getApiErrorMessage(e))}finally{setBusy(false)}}
 async function addField(){setBusy(true);setError("");try{await createPlatformField({table:table.id,...newField});setNewField({name:"",logical_type:"STRING",nullable:true});setAddOpen(false);await onChanged?.()}catch(e){setError(getApiErrorMessage(e))}finally{setBusy(false)}}
 return <div className="fieldRulesManager"><div className="relationManagerHeader"><div><span className="eyebrow">PLATFORM CONTENT</span><h2>Column content rules</h2><p>Source columns from External and Private Gateway remain read-only. Platform-created columns can be filled manually or calculated with DAX, SQL or Python.</p></div><button className="iconButton" onClick={onClose}>×</button></div>{error&&<Alert type="error">{error}</Alert>}
  <div className="fieldRulesToolbar"><label>Table<select value={tableId} onChange={e=>setTableId(e.target.value)}>{tables.map(t=><option key={t.id} value={t.id}>{t.technical_name||t.table_name}</option>)}</select></label><span className={`sourceModeBadge ${source?.mode?.toLowerCase()}`}>{source?.mode||"—"}</span><button className="button secondaryButton" onClick={()=>setAddOpen(v=>!v)}>+ Add platform column</button></div>
  {source?.mode!=="MANAGED"&&<div className="readOnlySourceNotice"><strong>Source-protected table</strong><span>Original columns are read-only. New columns are platform overlays and do not ALTER the external/private database.</span></div>}
  {addOpen&&<div className="platformFieldCreator"><label>Name<input value={newField.name} onChange={e=>setNewField(v=>({...v,name:e.target.value}))}/></label><label>Type<select value={newField.logical_type} onChange={e=>setNewField(v=>({...v,logical_type:e.target.value}))}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label className="checkboxLine"><input type="checkbox" checked={newField.nullable} onChange={e=>setNewField(v=>({...v,nullable:e.target.checked}))}/> Nullable</label><button className="button primaryButton" disabled={busy||!newField.name} onClick={addField}>Add column</button></div>}
  <div className="fieldRuleList">{(table?.fields||[]).map(f=>{const can=editable(f),d=drafts[f.id]||{mode:"MANUAL",expression:""};return <article className={`fieldRuleRow ${can?"":"locked"}`} key={f.id}><div className="fieldRuleIdentity"><span className="fieldTypeGlyph">{String(f.logical_type).match(/INT|DECIMAL|FLOAT|NUMBER/) ? "#":"◫"}</span><div><strong>{f.business_name||f.name}</strong><small>{f.logical_type} · {f.origin==="PLATFORM"?"Platform column":"Source column"}</small></div>{!can&&<span className="lockBadge">Read only</span>}</div><div className="fieldRuleControls"><label>Content mode<select disabled={!can} value={d.mode} onChange={e=>patch(f.id,{mode:e.target.value})}>{MODES.map(m=><option key={m} value={m}>{m==="MANUAL"?"Manual fill":m}</option>)}</select></label>{d.mode!=="MANUAL"&&<label className="ruleCodeLabel">Expression / code<textarea disabled={!can} value={d.expression} onChange={e=>patch(f.id,{expression:e.target.value})} placeholder={d.mode==="DAX"?"[quantity] * [unit_price]":d.mode==="SQL"?'"quantity" * "unit_price"':'def column(row):\n    return row["quantity"] * row["unit_price"]'}/></label>}<button className="button secondaryButton" disabled={!can||busy} onClick={()=>save(f)}>Save</button></div></article>})}</div>
 </div>
}
