"use client";
import {useMemo,useState} from "react";
import Icon from "@/components/ui/Icon";
import SharedDataPanel from "@/components/data/SharedDataPanel";
function Row({label,value}){return <div className="modelPropertyRow"><span>{label}</span><strong>{value??"—"}</strong></div>}
function Group({title,count,children,open=false}){return <details className="modelPropertyGroup" open={open}><summary><span>{title}</span>{count!==undefined&&<small>{count}</small>}</summary><div className="modelPropertyGroupBody">{children}</div></details>}
export default function ModelInspector({table,source,relations,tables,models=[],onMeasure,onSelect,onRenameTable,onDeleteTable,onDeleteSource,sources=[],onCollapse}){
 const [tab,setTab]=useState("data"),[query,setQuery]=useState("");
 const q=query.trim().toLowerCase();
 const tableById=useMemo(()=>Object.fromEntries(tables.map(t=>[t.id,t])),[tables]);
 if(!table)return <aside className="modelInspector powerModelInspector"><div className="powerPaneHeader unifiedPanelHeader"><div><strong>Data</strong><span>No table selected</span></div>{onCollapse&&<button type="button" className="panelCollapseButton" onClick={onCollapse} title="Collapse Data">›</button>}</div><SharedDataPanel tables={tables} models={models} activeTableId={null} onTable={onSelect} onRenameTable={onRenameTable} onDeleteTable={onDeleteTable} onDeleteSource={onDeleteSource} sourceById={Object.fromEntries(sources.map(s=>[s.id,s]))} className="powerTableDataPane modelDashboardDataPane"/></aside>;
 const inbound=relations.filter(r=>r.target_table===table.id),outbound=relations.filter(r=>r.source_table===table.id);
 return <aside className="modelInspector powerModelInspector">
  <div className="powerPaneHeader unifiedPanelHeader"><div><strong>{tab==="data"?"Data":"Table"}</strong><span>{table.technical_name||table.table_name}</span></div>{onCollapse&&<button type="button" className="panelCollapseButton" onClick={onCollapse} title="Collapse panel">›</button>}</div>
  <div className="powerPaneTabs"><button className={tab==="data"?"active":""} onClick={()=>setTab("data")}>Data</button><button className={tab==="table"?"active":""} onClick={()=>setTab("table")}>Table</button></div>
  {tab==="data"?<SharedDataPanel onMeasure={onMeasure} tables={tables} models={models} activeTableId={table.id} onTable={onSelect} onRenameTable={onRenameTable} onDeleteTable={onDeleteTable} onDeleteSource={onDeleteSource} sourceById={Object.fromEntries(sources.map(s=>[s.id,s]))} className="powerTableDataPane modelDashboardDataPane"/> :
  <div className="modelTableProperties"><div className="modelInspectorIdentity"><Icon name="table" size={18}/><div><strong>{table.technical_name||table.table_name}</strong><span>{table.schema_name} · {source?.name||"Source"}</span></div></div><Group title="Definition" open><Row label="Object" value={table.object_type}/><Row label="Primary Key" value={(table.primary_key_columns||[]).join(", ")||"—"}/><Row label="Row version" value={table.row_version_column||"—"}/></Group><Group title="Fields" count={table.fields?.length||0}>{(table.fields||[]).map(f=><div className="modelCompactField" key={f.id}><span>{f.is_primary_key?"PK":f.origin==="PLATFORM"?"P":""}</span><strong>{f.business_name||f.name}</strong><code>{f.logical_type}</code></div>)}</Group><Group title="Relations" count={inbound.length+outbound.length}>{!inbound.length&&!outbound.length?<span className="treeEmptyLabel">No registered relationships</span>:<>{outbound.map(r=><div className="modelCompactRelation" key={r.id}><span>OUT</span><strong>{r.name}</strong><small>→ {tableById[r.target_table]?.table_name||r.target}</small></div>)}{inbound.map(r=><div className="modelCompactRelation" key={r.id}><span>IN</span><strong>{r.name}</strong><small>← {tableById[r.source_table]?.table_name||r.source}</small></div>)}</>}</Group><Group title="Mode"><Row label="Mode" value={source?.mode||"—"}/><Row label="Source" value={source?.name||"—"}/></Group></div>}
 </aside>
}
