# Generated by Django 6.0.8 on 2026-09-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_gateway', '0002_gatewayimportrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gatewayjob',
            new_name='customer_ga_gateway_8b7ec7_idx',
            old_name='customer_ga_gateway_4dcf35_idx',
        ),
    ]
