# Generated by Django 6.0.8 on 2026-09-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_gateway', '0003_gatewayjob_query_plan'),
        ('customer_gateway', '0003_rename_customer_ga_gateway_4dcf35_idx_customer_ga_gateway_8b7ec7_idx'),
    ]

    operations = [
    ]
