import uuid
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('common','0001_scriptblock'),('workspaces','0001_initial')]
 operations=[
  migrations.AlterField(model_name='scriptblock',name='purpose',field=models.CharField(blank=True,default='',max_length=24)),
  migrations.CreateModel(name='ComputeTarget',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=160)),('kind',models.CharField(choices=[('PLATFORM','Platform compute'),('CUSTOMER','Customer compute')],default='PLATFORM',max_length=16)),('agent_key',models.CharField(blank=True,max_length=180)),('status',models.CharField(default='DRAFT',max_length=20)),('capabilities',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('workspace',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='compute_targets',to='workspaces.workspace'))]),
  migrations.CreateModel(name='PythonEnvironment',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=160)),('python_version',models.CharField(default='3.13',max_length=32)),('status',models.CharField(default='DRAFT',max_length=20)),('version',models.PositiveIntegerField(default=1)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('compute_target',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='environments',to='common.computetarget')),('workspace',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='python_environments',to='workspaces.workspace'))]),
  migrations.CreateModel(name='EnvironmentPackage',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=160)),('version_spec',models.CharField(blank=True,max_length=80)),('status',models.CharField(default='REQUESTED',max_length=20)),('source',models.CharField(default='PYPI',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('environment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='packages',to='common.pythonenvironment'))],options={'unique_together':{('environment','name')}}),
  migrations.CreateModel(name='ScriptArtifact',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('artifact_type',models.CharField(choices=[('TRANSFORMATION','Transformation'),('FIELD_RULE','Field rule'),('MEASURE','Measure'),('CHART','Chart'),('FUNCTION','Function'),('ML_MODEL','ML model'),('OPTIMIZATION','Optimization'),('DATASET','Dataset')],max_length=24)),('name',models.CharField(blank=True,max_length=220)),('object_type',models.CharField(blank=True,max_length=80)),('object_id',models.CharField(blank=True,max_length=80)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('script_block',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='artifacts',to='common.scriptblock'))]),
 ]
