"use client";
import {useEffect,useMemo,useState} from "react";
import {useWorkspace} from "@/lib/hooks/useWorkspace";
import {analyzeScript,createScriptBlock,deleteScriptBlock,listScriptBlocks,updateScriptBlock,publishScriptBlock,executeScriptBlock,publishPythonVariable,registerPythonMLModel} from "@/lib/services/scripts";
import {readCodeDrafts,writeCodeDraft} from "@/lib/storage/codeDrafts";
import {deleteMetric} from "@/lib/services/metrics";
import EmptyState from "@/components/ui/EmptyState";
import ScriptWorkbench from "@/components/data/ScriptWorkbench";
import Icon from "@/components/ui/Icon";
import WorkspaceCommandBar from "@/components/data/WorkspaceCommandBar";
const listValue=v=>Array.isArray(v)?v:v?.results||[];
const newDraft=(language="PYTHON",afterId=null)=>({afterId,id:`draft-${Date.now()}-${Math.random().toString(36).slice(2)}`,language,code:"",busy:false,validation:null});
const artifactNames=item=>(item.artifacts||[]).map(a=>a.name).filter(Boolean);
const references=(code,names)=>names.some(name=>new RegExp(`(^|[^A-Za-z0-9_])${String(name).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}([^A-Za-z0-9_]|$)`,"i").test(code||""));
function NotebookOutput({output,onPublish,publishing}){
 if(!output)return null;
 const variables=output.variables||[];
 const autoPublished=output.auto_published||[];
 const autoPublishedNames=new Set(autoPublished.map(x=>x?.dataset?.name).filter(Boolean));
 const dataVariables=variables.filter(v=>(v.kind==="dataframe"||v.kind==="scalar")&&!autoPublishedNames.has(v.name));
 const mlVariables=variables.filter(v=>v.kind==="ml_model");
 const registrations=output.ml_registrations||[];
 const optimizationRegistrations=output.optimization_registrations||[];
 const publishBar=<>{autoPublished.length?<div className="pythonPublishBar pythonPublishedBar"><span>Published to Data</span>{autoPublished.map(x=><span className="pythonPublishedChip" key={x?.dataset?.id||x?.dataset?.name}>{x?.dataset?.name} · Table</span>)}</div>:null}{registrations.length?<div className="mlRegistrationNotice"><strong>Data Science</strong>{registrations.map(r=><span key={r.model_version_id}>{r.name} · v{r.version} · {r.task_type?.replaceAll("_"," ")}</span>)}</div>:null}{optimizationRegistrations.length?<div className="mlRegistrationNotice optimizationRegistrationNotice"><strong>Optimization</strong>{optimizationRegistrations.map(r=><span key={r.model_id}>{r.name} · {r.status}{r.run_id?" · run queued":""}</span>)}</div>:null}{dataVariables.length?<div className="pythonPublishBar"><span>Publish to Data</span>{dataVariables.map(v=><button key={v.name} type="button" disabled={publishing} onClick={()=>onPublish?.(v)}>{v.name} · {v.kind==="dataframe"?"Table":"Measure"}</button>)}</div>:null}{mlVariables.length?<div className="pythonPublishBar mlPublishBar"><span>Register in Data Science</span>{mlVariables.map(v=><button key={v.name} type="button" disabled={publishing} onClick={()=>onPublish?.(v)} title={`Register ${v.class_name||"ML model"}`}>{v.name} · {v.class_name||"ML model"}</button>)}</div>:null}</>;
 let body=null;
 if(output.kind==="image")body=<div className="notebookOutput notebookImageOutput"><img src={`data:${output.mime_type||"image/png"};base64,${output.data}`} alt="Python output"/>{output.stdout?<pre className="notebookStdout">{output.stdout}</pre>:null}</div>;
 else if(output.kind==="table")body=<div className="notebookOutput"><div className="notebookOutputMeta">{output.row_count??output.rows?.length??0} row(s){output.truncated?" · preview":""}</div><div className="notebookOutputTableWrap"><table><thead><tr>{(output.columns||[]).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{(output.rows||[]).map((row,i)=><tr key={i}>{(output.columns||[]).map(c=><td key={c}>{String(row?.[c]??"")}</td>)}</tr>)}</tbody></table></div>{output.stdout?<pre className="notebookStdout">{output.stdout}</pre>:null}</div>;
 else body=output.text?<pre className="notebookOutput notebookStdout">{output.text}</pre>:null;
 return <>{body}{publishBar}</>;
}
function SavedCell({item,index,onReload,onDelete,onAddNext,onMove,canUp,canDown,dependent}){
 const [language,setLanguage]=useState(item.language),[code,setCode]=useState(item.code),[busy,setBusy]=useState(false),[validation,setValidation]=useState(null);
 useEffect(()=>{setLanguage(item.language);setCode(item.code);setValidation(null)},[item.id,item.updated_at]);
 async function run({addNext=false}={}){if(!code.trim()||busy)return;setBusy(true);try{const check=await analyzeScript(language,code);setValidation(check);if(check?.valid===false)return;await updateScriptBlock(item.id,{language,code,status:"SAVED",context:{...(item.context||{}),notebook_order:item.context?.notebook_order??index}});const executionOutput=await executeScriptBlock(item.id);const published=await publishScriptBlock(item.id);setValidation({valid:true,detail:published.output_type==="MEASURES"?`${published.measures?.length||0} measure(s) published to Data.`:published.output_type==="DATASET"?`Dataset published to Data.`:"Code saved."});window.dispatchEvent(new CustomEvent("bi-data-artifacts-changed",{detail:{workspace:item.workspace}}));await onReload();if(addNext)onAddNext(language)}catch(error){setValidation({valid:false,error:error?.response?.data?.detail||error?.response?.data?.error||error?.message||"The code could not be published."})}finally{setBusy(false)}}
 async function publishVariable(variable){setBusy(true);try{if(variable.kind==="ml_model"){const result=await registerPythonMLModel(item.id,variable.name,variable.name);setValidation({valid:true,detail:`${result.name} v${result.version} registered in Data Science.`});window.dispatchEvent(new CustomEvent("bi-ml-artifacts-changed",{detail:{workspace:item.workspace}}));}else{const result=await publishPythonVariable(item.id,variable.name,variable.name);setValidation({valid:true,detail:result.output_type==="DATASET"?`${variable.name} published as a table in Data.`:`${variable.name} published as a measure in Data.`});window.dispatchEvent(new CustomEvent("bi-data-artifacts-changed",{detail:{workspace:item.workspace}}));}await onReload()}catch(error){setValidation({valid:false,error:error?.response?.data?.detail||error.message})}finally{setBusy(false)}}
 async function remove(){if(!window.confirm("Delete this code block and any measures it defines?"))return;setBusy(true);try{await onDelete(item)}catch(error){setValidation({valid:false,error:error?.response?.data?.detail||error.message})}finally{setBusy(false)}}
 const meta=<><div className="notebookExecutionMeta">{(item.artifacts||[]).slice(0,3).map(a=><span key={a.id||`${a.artifact_type}-${a.name}`}>{a.artifact_type.replaceAll("_"," ")}</span>)}</div><button type="button" className="notebookDelete inlineDelete" aria-label="Delete code block" title="Delete block" onClick={remove}>×</button></>;
 return <article className={`notebookCell streamlinedNotebookCell codeHoverCell ${dependent?"dependentScriptCell":""}`}><div className="notebookPromptVisible">In [{index+1}]</div><div className="notebookCellBody"><ScriptWorkbench language={language} onLanguage={setLanguage} code={code} onCode={setCode} onCommit={run} busy={busy} validation={validation} toolbarEnd={meta}/><NotebookOutput output={item.context?.notebook_output} onPublish={publishVariable} publishing={busy}/>{dependent?<div className="dependencyWarning">This block depends on an artifact from the deleted block. Review it or undo the deletion.</div>:null}<button type="button" className="inlineInsertZone" onClick={()=>onAddNext(language,item.id)} aria-label="Insert code block below"><span>+</span></button></div><div className="blockMoveRail"><button type="button" disabled={!canUp} onClick={()=>onMove(item.id,-1)} title="Move block up" aria-label="Move block up"><Icon name="chevronDown" size={16}/></button><button type="button" disabled={!canDown} onClick={()=>onMove(item.id,1)} title="Move block down" aria-label="Move block down"><Icon name="chevronDown" size={16}/></button></div></article>
}
function SharedDraftCell({draft,workspace,onReload}){
 const [busy,setBusy]=useState(false),[validation,setValidation]=useState(null);
 function patch(changes){writeCodeDraft(workspace,draft.id,{...draft,...changes});setValidation(null)}
 async function save(){
  if(busy)return;
  setBusy(true);
  try{
   const check=await analyzeScript(draft.language,draft.code);setValidation(check);
   if(check?.valid===false)return;
   const saved=await createScriptBlock({workspace,name:`${draft.language} · ${new Date().toLocaleString()}`,purpose:"",language:draft.language,code:draft.code,context:{source:draft.source},linked_object_type:draft.metricId?"METRIC":"",linked_object_id:draft.metricId||"",status:"SAVED"});
   await publishScriptBlock(saved.id);window.dispatchEvent(new CustomEvent("bi-data-artifacts-changed",{detail:{workspace}}));
   writeCodeDraft(workspace,draft.id,null);await onReload();
  }catch(error){setValidation({valid:false,error:error?.response?.data?.detail||error.message})}finally{setBusy(false)}
 }
 async function remove(){
  if(draft.metricId&&!window.confirm("Delete this measure and its code blocks?"))return;
  setBusy(true);
  try{if(draft.metricId)await deleteMetric(draft.metricId);writeCodeDraft(workspace,draft.id,null);await onReload()}
  catch(error){if(error?.response?.status===404){writeCodeDraft(workspace,draft.id,null)}else setValidation({valid:false,error:error?.response?.data?.detail||error.message})}
  finally{setBusy(false)}
 }
 return <article className="notebookCell notebookDraftCell streamlinedNotebookCell"><div className="notebookCellBody"><ScriptWorkbench language={draft.language} code={draft.code} onLanguage={language=>patch({language})} onCode={code=>patch({code})} onCommit={save} busy={busy} validation={validation} toolbarEnd={<><span>Draft · {draft.source}</span><button type="button" disabled={busy} onClick={save}>Save</button><button type="button" disabled={busy} aria-label="Remove draft" onClick={remove}>×</button></>}/></div></article>
}
export default function ScriptsPage(){
 const {activeWorkspace}=useWorkspace();
 const [sharedDrafts,setSharedDrafts]=useState([]);
 useEffect(()=>{const refresh=()=>setSharedDrafts(readCodeDrafts(activeWorkspace?.id));refresh();window.addEventListener("bi-code-drafts-changed",refresh);window.addEventListener("storage",refresh);return()=>{window.removeEventListener("bi-code-drafts-changed",refresh);window.removeEventListener("storage",refresh)}},[activeWorkspace?.id]);const [items,setItems]=useState([]),[drafts,setDrafts]=useState([]),[undo,setUndo]=useState(null),[dependentIds,setDependentIds]=useState([]);
 async function load(){if(activeWorkspace?.id){const rows=listValue(await listScriptBlocks(activeWorkspace.id));setItems(rows.sort((a,b)=>(a.context?.notebook_order??Number.MAX_SAFE_INTEGER)-(b.context?.notebook_order??Number.MAX_SAFE_INTEGER)||String(a.created_at).localeCompare(String(b.created_at))))}}
 useEffect(()=>{load();const reload=event=>{if(String(event.detail.workspace)===String(activeWorkspace?.id))load()};window.addEventListener("bi-code-deleted",reload);return()=>window.removeEventListener("bi-code-deleted",reload)},[activeWorkspace?.id]);
 function addBlock(language="PYTHON",afterId=null){setDrafts(current=>[...current,newDraft(language,afterId)])}
 function patchDraft(id,patch){setDrafts(current=>current.map(d=>d.id===id?{...d,...patch}:d))}
 async function commitDraft(draft,{addNext=false}={}){if(!activeWorkspace?.id||!draft.code.trim()||draft.busy)return;patchDraft(draft.id,{busy:true});let saved=null;try{const check=await analyzeScript(draft.language,draft.code);patchDraft(draft.id,{validation:check});if(check?.valid===false)return;const afterIndex=draft.afterId?items.findIndex(x=>String(x.id)===String(draft.afterId)):-1;const order=afterIndex>=0?(items[afterIndex]?.context?.notebook_order??afterIndex)+0.5:items.length+drafts.indexOf(draft);saved=await createScriptBlock({workspace:activeWorkspace.id,name:`${draft.language} · ${new Date().toLocaleString()}`,language:draft.language,purpose:"",code:draft.code,context:{section:"notebook",notebook_order:order},status:"SAVED"});await executeScriptBlock(saved.id);const published=await publishScriptBlock(saved.id);patchDraft(draft.id,{validation:{valid:true,detail:published.output_type==="MEASURES"?`${published.measures?.length||0} measure(s) published to Data.`:published.output_type==="DATASET"?`Dataset published to Data.`:"Code saved."}});window.dispatchEvent(new CustomEvent("bi-data-artifacts-changed",{detail:{workspace:activeWorkspace.id}}));setDrafts(current=>current.filter(d=>d.id!==draft.id));await load();if(addNext)addBlock(draft.language)}catch(error){const detail=error?.response?.data?.detail||error?.response?.data?.error||error?.message||"The code could not be published.";patchDraft(draft.id,{validation:{valid:false,error:detail}});if(saved){try{await deleteScriptBlock(saved.id)}catch(_cleanupError){}saved=null}}finally{patchDraft(draft.id,{busy:false})}}
 async function moveSaved(id,direction){const index=items.findIndex(x=>String(x.id)===String(id));const target=index+direction;if(index<0||target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];setItems(next);await Promise.all(next.map((item,i)=>updateScriptBlock(item.id,{context:{...(item.context||{}),notebook_order:i}})));await load()}
 async function removeSaved(item){const names=artifactNames(item);const affected=items.filter(x=>x.id!==item.id&&references(x.code,names)).map(x=>x.id);const result=await deleteScriptBlock(item.id);await load();setDependentIds(affected);setUndo(result?.deleted_metric_ids?.length?null:{item,affected})}
 async function undoDelete(){if(!undo||!activeWorkspace?.id)return;const x=undo.item;await createScriptBlock({workspace:activeWorkspace.id,name:x.name,language:x.language,purpose:x.purpose||"",code:x.code,context:x.context||{section:"notebook"},status:x.status||"SAVED"});setUndo(null);setDependentIds([]);await load()}
 if(!activeWorkspace)return <EmptyState title="Select a workspace"/>;
 const empty=items.length===0&&drafts.length===0&&sharedDrafts.length===0;
 return <div className="pageStack scriptsPage codeWorkspacePage"><WorkspaceCommandBar view="code"><div className="codeToolbarMeta"><span>{items.length+drafts.length+sharedDrafts.length} block{items.length+drafts.length+sharedDrafts.length===1?"":"s"}</span><span className="codeEnvironmentSingle">Workspace Python</span></div><button type="button" className="codeNewBlockButton" onClick={()=>addBlock()} title="Add code block" aria-label="Add code block"><Icon name="plus" size={15}/><span>New block</span></button></WorkspaceCommandBar>
  {undo?<div className="scriptUndoBar"><span>Block deleted. {undo.affected.length?`${undo.affected.length} dependent block(s) highlighted.`:""}</span><button type="button" onClick={undoDelete}>Undo change</button></div>:null}
  <section className="scriptNotebook codeWorkspaceNotebook">
   {empty?<div className="codeEmptyWelcome"><span className="codeEmptyIcon"><Icon name="code" size={22}/></span><strong>Start a code workflow</strong><p>Create a Python, SQL or DAX block. Keep reusable analysis logic together with the workspace.</p></div>:null}
   {sharedDrafts.map(draft=><SharedDraftCell key={draft.id} draft={draft} workspace={activeWorkspace.id} onReload={load}/>)}
   {items.map((x,i)=><div className="notebookSequence" key={x.id}><SavedCell item={x} index={i} onReload={load} onDelete={removeSaved} onAddNext={addBlock} onMove={moveSaved} canUp={i>0} canDown={i<items.length-1} dependent={dependentIds.includes(x.id)}/>{drafts.filter(d=>String(d.afterId)===String(x.id)).map((draft,index)=>{const meta=<><div className="notebookExecutionMeta"><span>Draft</span></div><button type="button" className="notebookDelete inlineDelete" title="Remove draft" aria-label="Remove draft" onClick={()=>setDrafts(c=>c.filter(d=>d.id!==draft.id))}>×</button></>;return <article className="notebookCell notebookDraftCell streamlinedNotebookCell" key={draft.id}><div className="notebookPromptVisible">In [{items.length+index+1}]</div><div className="notebookCellBody"><ScriptWorkbench language={draft.language} onLanguage={language=>patchDraft(draft.id,{language,validation:null})} code={draft.code} onCode={code=>patchDraft(draft.id,{code,validation:null})} onCommit={opts=>commitDraft(draft,opts)} busy={draft.busy} validation={draft.validation} toolbarEnd={meta} autoFocus/><button type="button" className="inlineInsertZone" onClick={()=>addBlock(draft.language,draft.id)} aria-label="Insert code block below"><span>+</span></button></div></article>})}</div>)}
   {drafts.filter(d=>!d.afterId||!items.some(x=>String(x.id)===String(d.afterId))).map((draft,index)=>{const meta=<><div className="notebookExecutionMeta"><span>Draft</span></div><button type="button" className="notebookDelete inlineDelete" title="Remove draft" aria-label="Remove draft" onClick={()=>setDrafts(c=>c.filter(d=>d.id!==draft.id))}>×</button></>;return <article className="notebookCell notebookDraftCell streamlinedNotebookCell codeHoverCell" key={draft.id}><div className="notebookPromptVisible">In [{items.length+index+1}]</div><div className="notebookCellBody"><ScriptWorkbench language={draft.language} onLanguage={language=>patchDraft(draft.id,{language,validation:null})} code={draft.code} onCode={code=>patchDraft(draft.id,{code,validation:null})} onCommit={opts=>commitDraft(draft,opts)} busy={draft.busy} validation={draft.validation} toolbarEnd={meta} autoFocus/><button type="button" className="inlineInsertZone" onClick={()=>addBlock(draft.language,draft.id)} aria-label="Insert code block below"><span>+</span></button></div></article>})}
   {!empty?<button type="button" className="notebookAddZone compactAddZone" onClick={()=>addBlock(drafts.at(-1)?.language||items.at(-1)?.language||"PYTHON")}><Icon name="plus" size={16}/><span>Add code block</span></button>:null}
  </section>
 </div>
}
