"use client";
import {useEffect,useMemo,useState} from "react";
import {listRecords} from "@/lib/services/records";
import {tableLabel} from "@/lib/tableIdentity";
const OPS=[['eq','Equals'],['ne','Not equal'],['contains','Contains'],['gt','Greater than'],['gte','Greater or equal'],['lt','Less than'],['lte','Less or equal']];
export default function ExportJobForm({workspaceId,tables,onSubmit,isSaving,maxRows=500000}){
 const[tableId,setTableId]=useState(""),[type,setType]=useState("XLSX"),[limit,setLimit]=useState(Math.min(100000,maxRows)),[columns,setColumns]=useState([]),[filters,setFilters]=useState([]),[rows,setRows]=useState([]),[loading,setLoading]=useState(false);
 const table=useMemo(()=>tables.find(t=>t.id===tableId),[tables,tableId]);const fields=table?.fields||[];
 useEffect(()=>{if(tableId)setColumns(fields.map(f=>f.name));else setColumns([]);setFilters([])},[tableId]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{let live=true;if(!tableId){setRows([]);return;}setLoading(true);listRecords(tableId,{limit:12,filters}).then(r=>live&&setRows(r.rows||[])).catch(()=>live&&setRows([])).finally(()=>live&&setLoading(false));return()=>{live=false}},[tableId,JSON.stringify(filters)]); // eslint-disable-line react-hooks/exhaustive-deps
 function toggle(c){setColumns(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c])}function filterFor(name){return filters.find(f=>f.field===name)||{field:name,operator:'eq',value:''}}function setFilter(name,key,value){setFilters(v=>{const current=filterFor(name),next={...current,[key]:value};return [...v.filter(f=>f.field!==name),next]})}
 function submit(e){e.preventDefault();onSubmit({workspace:workspaceId,source_table:tableId,file_type:type,columns,filters:filters.filter(f=>f.value!==""),row_limit:Number(limit)})}
 return <form className="exportStudio" onSubmit={submit}><div className="formGrid twoColumns"><label className="field"><span>Source table</span><select value={tableId} onChange={e=>setTableId(e.target.value)} required><option value="">Select table…</option>{tables.map(t=><option key={t.id} value={t.id}>{tableLabel(t)}</option>)}</select></label><label className="field"><span>Format</span><select value={type} onChange={e=>setType(e.target.value)}><option value="XLSX">Excel</option><option value="CSV">CSV</option></select></label></div>
 {table&&<><div className="exportPreviewMeta"><strong>{columns.length} / {fields.length} columns selected</strong><span>{filters.filter(f=>f.value!=="").length} filters · preview {rows.length} rows</span></div><div className="tableWrap exportInteractivePreview"><table className="dataTable"><thead><tr>{fields.map(f=>{const active=columns.includes(f.name),flt=filterFor(f.name);return <th key={f.name} className={active?"exportColumnSelected":"exportColumnMuted"}><button type="button" className="exportColumnHeader" onClick={()=>toggle(f.name)}>{active?"✓ ":""}{f.name}</button><div className="exportColumnFilter"><select value={flt.operator} onChange={e=>setFilter(f.name,'operator',e.target.value)}>{OPS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input value={flt.value} onChange={e=>setFilter(f.name,'value',e.target.value)} placeholder="Filter…"/></div></th>})}</tr></thead><tbody>{loading?<tr><td colSpan={fields.length}>Loading preview…</td></tr>:rows.map((r,i)=><tr key={i}>{fields.map(f=><td key={f.name}>{r[f.name]==null?"NULL":String(r[f.name])}</td>)}</tr>)}</tbody></table></div></>}
 <div className="formGrid twoColumns"><label className="field"><span>Maximum rows</span><input type="number" min="1" max={maxRows} value={limit} onChange={e=>setLimit(e.target.value)}/></label></div><div className="formActions"><button className="button primaryButton" disabled={isSaving||!tableId}>{isSaving?"Preparing…":"Export"}</button></div></form>
}
